### ISSUE TITLE
SQLiteBlobTooBigException crash loop

### ISSUE THREAD

**Issue by georgedorn** [wallabag/android-app#1010]
Once this error starts, the only fix is to delete all app data and set authentication back up.

Recreating the error is tricky.  Sometimes it just happens after a background sync, sometimes it isn't triggered until I switch from favorites to unread a few times.  I suspect it's a bad entry in my self-hosted instance (which is running 2.3.8).

# Environment details
- **wallabag app version**:  2.0.2
- **wallabag app installation source** F-Droid
- **Android OS version**: 9
- **Android ROM**: LineageOS 16.0
- **Android hardware**: OnePlus X
- **wallabag server version**: 2.3.8
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## android logcat
```
FATAL EXCEPTION: main
Process: fr.gaulupeau.apps.InThePoche, PID: 6936
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=11, totalRows=12
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
        at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
        at org.greenrobot.greendao.AbstractDao.moveToNextUnlocked(AbstractDao.java:521)
        at org.greenrobot.greendao.AbstractDao.loadAllUnlockOnWindowBounds(AbstractDao.java:501)
        at org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java:480)
        at org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:203)
        at org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
        at org.greenrobot.greendao.query.Query.list(Query.java:89)
        at org.greenrobot.greendao.query.QueryBuilder.list(QueryBuilder.java:427)
        at fr.gaulupeau.apps.Poche.ui.ArticleListFragment.getItems(ArticleListFragment.java:183)
        at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment.resetContent(RecyclerViewListFragment.java:177)
        at fr.gaulupeau.apps.Poche.ui.ArticleListFragment.resetContent(ArticleListFragment.java:169)
        at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment.checkList(RecyclerViewListFragment.java:158)
        at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment.onResume(RecyclerViewListFragment.java:106)
```

**Comment by georgedorn** [comment]
This is the latest version on F-Droid, so I don't think it's fixed, as suggested by https://github.com/wallabag/android-app/issues/785

**Comment by tcitworld** [comment]
Latest stable version on F-Droid is version 2.3.0, and you said to have 2.0.2.

**Comment by di72nn** [comment]
Fixed in `master` and `beta.3` (the beta is available as [APK](https://github.com/wallabag/android-app/releases/tag/2.4.0-beta.3), [beta on Google Play](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche), [eventually on F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7000) (still not as "stable" version, but I do recommend installing it)).

**Comment by georgedorn** [comment]
> Latest stable version on F-Droid is version 2.3.0, and you said to have 2.0.2.

I triple-checked, 2.0.2 was the latest version on F-Droid.  So this morning I uninstalled the wallabag app entirely, and _now_ F-Droid tells me 2.3.0 and 2.4.0-beta.1 are available.  I'm not sure if that's a bug with F-Droid, my phone, or the wallabag app's F-Droid configuration, but worth noting in case anybody else runs into this.

**Comment by tcitworld** [comment]
Maybe you installed the wallabag app through another way than F-Droid ? It doesn't shows F-Droid versions if the current installation doesn't come from their store.
