### ISSUE TITLE
Random crash in settings

### ISSUE THREAD

**Issue by di72nn** [wallabag/android-app#1037]
```
2020-08-13 22:21:36.848 7792-7792/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.gaulupeau.apps.InThePoche.dev, PID: 7792
    java.lang.IllegalStateException: Fragment SettingsFragment{7cfaa20} not attached to Activity
        at android.app.Fragment.getResources(Fragment.java:768)
        at android.app.Fragment.getString(Fragment.java:790)
        at fr.gaulupeau.apps.Poche.ui.preferences.SettingsActivity$SettingsFragment.updateSummary(SettingsActivity.java:696)
        at fr.gaulupeau.apps.Poche.ui.preferences.SettingsActivity$SettingsFragment.onSharedPreferenceChanged(SettingsActivity.java:448)
        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
        at android.app.SharedPreferencesImpl$EditorImpl.lambda$notifyListeners$0(SharedPreferencesImpl.java:613)
        at android.app.-$$Lambda$SharedPreferencesImpl$EditorImpl$3CAjkhzA131V3V-sLfP2uy0FWZ0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by di72nn** [comment]
Same crash in the GPlay Console on Android 9.

But it is not a new one: another one on Android 7 with app version 219.
