### ISSUE TITLE
error upon deletion

### ISSUE THREAD

**Issue by mvhulten** [wallabag/android-app#1101]
I get this error each time when removing any article from my UNREAD list, though the article is removed:

```
Onbekende foutmelding
com.squareup.moshi.JsonDataException: Expected an int but was NULL at path $.id
Stacktrace:
com.squareup.moshi.JsonDataException: Expected an int but was NULL at path $.id
	at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:912)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:173)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:171)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.deleteArticleWithObject(WallabagService.java:698)
	at wallabag.apiwrapper.WallabagService.lambda$deleteArticle$3$WallabagService(WallabagService.java:666)
	at wallabag.apiwrapper.-$$Lambda$WallabagService$Q342ppA72MGOP6dbbn-eFJ0O6e0.run(Unknown Source:6)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
	at wallabag.apiwrapper.WallabagService.deleteArticle(WallabagService.java:662)
	at wallabag.apiwrapper.WallabagService.deleteArticle(WallabagService.java:638)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:138)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
	at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$Nf0ej7UkvM-IGhcyH2GG-UaljDo.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$gjfracnqY8x0_-mrxsx0oqjQmgk(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$gjfracnqY8x0_-mrxsx0oqjQmgk.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)
```

I use Wallabag from F-Droid and a Framabag account.

**Comment by di72nn** [comment]
Sorry, but that's [Framabag's issue](https://github.com/wallabag/android-app/issues/1076#issuecomment-708970634).
