### ISSUE TITLE
Cannot sync with my own server after updating it to v2.4

### ISSUE THREAD

**Issue by kix2902** [wallabag/android-app#1121]
# Issue details

### Duplicate?
I found some issues with other JSON errors but none with my exact case

### Actual behaviour
- After updating my server to Wallabag 2.4 every time I sent an url to the app it keeped crashing. I uninstalled the app to avoid problems with old data but error now appears at the login process.

### Expected behaviour
- App should accept new urls.

# Steps to reproduce the issue
1. Install the app
2. Follow the configuration assistant 
3. Nothing happens

# Environment details
- **wallabag app version**: 2.4.2
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Play Store
- **Android OS version**: 11
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock
- **Android hardware**: Pixel 2 XL
- **wallabag server version**: 2.4.0
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs

## Android app
    com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
        at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:233)
        at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1051)
        at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:366)
        at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:193)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:134)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
        at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
        at wallabag.apiwrapper.WallabagService.getVersion(WallabagService.java:1449)
        at fr.gaulupeau.apps.Poche.network.tasks.TestApiAccessTask.doInBackground(TestApiAccessTask.java:101)
        at fr.gaulupeau.apps.Poche.network.tasks.TestApiAccessTask.doInBackground(TestApiAccessTask.java:16)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:

**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? App worked perfectly from June 2017 until the server update about a week ago.

**Comment by di72nn** [comment]
Do `Settings -> Miscellaneous -> Save logcat output to a file` after an error like that, I'll need to see the last attempted action before the error.

Also check your webserver log for any the errors.

**Comment by kix2902** [comment]
I reviewed my server but no errors are registered. 

Attached is the log file with the launch of the app and the connection testing, which is throwing the error.

[logcat_20201217_191013.txt](https://github.com/wallabag/android-app/files/5711342/logcat_20201217_191013.txt)

**Comment by kix2902** [comment]
I reinstalled the server app and all is working ok now, sorry for the incovenience.

**Comment by di72nn** [comment]
Wanna update that one-star review for an app that

> worked perfectly from June 2017

and turned out to be not broken after all?
