### ISSUE TITLE
App crashes when using quote character " in search

### ISSUE THREAD

**Issue by AnneLaureF** [wallabag/android-app#1125]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes

### Actual behaviour
- When I input the character " into the search box, the app crashes (it closes, and if I try a second time I get the Android toast "wallabag s'arrête automatiquement")

### Expected behaviour
- no crash. either " is ignored or it is used to search a whole phrase instead of individual words like in some search engine (that's what I wanted but I would have understood if it was just ignored)

# Steps to reproduce the issue
1. tap the search icon
2. input " into the box
3. 

# Environment details
- **wallabag app version**: 2.4.2 (228)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): F-Droid
- **Android OS version**: 9
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock Samsung (One UI 1.1)
- **Android hardware**: Samsung Galaxy Tab S5e
- **wallabag server version**: wallabag.it
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):
n/a

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:
n/a
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here!

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
Yes, I love it. The recent improvement in search performance was much appreciated.

**Comment by di72nn** [comment]
Thanks for the report!

Also crashes with stuff like "-foo".

<details>
<summary>Stacktrace</summary>

```
    android.database.sqlite.SQLiteException: malformed MATCH expression: ["] (code 1 SQLITE_ERROR)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
        at org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java:453)
        at org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:203)
        at org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
        at org.greenrobot.greendao.query.Query.list(Query.java:89)
        at org.greenrobot.greendao.query.QueryBuilder.list(QueryBuilder.java:425)
        at fr.gaulupeau.apps.Poche.ui.ArticleListFragment.getItems(ArticleListFragment.java:190)
        at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment.resetContent(RecyclerViewListFragment.java:174)
        at fr.gaulupeau.apps.Poche.ui.ArticleListFragment.resetContent(ArticleListFragment.java:176)
        at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment.checkList(RecyclerViewListFragment.java:155)
        at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment.invalidateList(RecyclerViewListFragment.java:148)
        at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment.setSearchQuery(RecyclerViewListFragment.java:142)
        at fr.gaulupeau.apps.Poche.ui.ArticleListsFragment.setSearchQueryOnFragment(ArticleListsFragment.java:176)
        at fr.gaulupeau.apps.Poche.ui.ArticleListsFragment.setSearchQuery(ArticleListsFragment.java:147)
        at fr.gaulupeau.apps.Poche.ui.MainActivity.setSearchQueryOnFragment(MainActivity.java:671)
        at fr.gaulupeau.apps.Poche.ui.MainActivity.setSearchQuery(MainActivity.java:666)
        at fr.gaulupeau.apps.Poche.ui.MainActivity.access$400(MainActivity.java:66)
        at fr.gaulupeau.apps.Poche.ui.MainActivity$3.onQueryTextChange(MainActivity.java:410)
        at androidx.appcompat.widget.SearchView.onTextChanged(SearchView.java:1187)
        at androidx.appcompat.widget.SearchView$10.onTextChanged(SearchView.java:1725)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9771)
        at android.widget.TextView.handleTextChanged(TextView.java:9868)
        at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12562)
        at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1263)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:575)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:506)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:36)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
        at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
</details>

**Comment by solkaz** [comment]
Commenting that this affects me on Android 11 (Pixel 3a, installed from Play Store). I noticed that the tags search does _not_ have this issue; only the articles search does.

**Comment by solkaz** [comment]
Digging into this, I've discovered a couple of things:
- The issue with the quotation marks (the original problem that @AnneLaureF reported) can be solved by replacing a single quotation mark with another one (see [this SO answer](https://stackoverflow.com/a/58138810))
- The issue concerning "-foo" (that @di72nn reported) was also [an issue with K-9](https://github.com/k9mail/k-9/issues/3653). In their case, [they chose to simply return an empty list if an error occurred](https://github.com/k9mail/k-9/pull/4958).

The relevant bit of code is [here](https://github.com/wallabag/android-app/blob/master/app/src/main/java/fr/gaulupeau/apps/Poche/ui/ArticleListFragment.java#L223)

I don't know what's the "right" solution; if that could be determined, I would be happy to help submit a PR.

**Comment by di72nn** [comment]
@solkaz thanks for looking into it.

> I noticed that the tags search does _not_ have this issue; only the articles search does.

Yeah, this happens only with full-text-search queries which are used only for articles.

I remember seeing that K-9 issue. What I don't remember is why I didn't comment on how it should be fixed in wallabag - perhaps I had some doubts.

Anyway, returning an empty list seems like a good approach.

> I would be happy to help submit a PR

Sure. Catching it around [this bit of code](https://github.com/wallabag/android-app/blob/c4de8bdecfaf03623f0eff65040bcf77f85807c1/app/src/main/java/fr/gaulupeau/apps/Poche/ui/ArticleListFragment.java#L190) should suffice.
I would probably do something like this:
```java
        try {
            return detachObjects(qb.list());
        } catch (SQLException e) {
            if (e.getMessage() != null && e.getMessage().contains("malformed MATCH expression")) {
                return new ArrayList<>();
            } else {
                throw e;
            }
        }
```

**Comment by solkaz** [comment]
@di72nn I've added a PR that implements your suggestion.
