### ISSUE TITLE
Error sweeping deleted articles

### ISSUE THREAD

**Issue by nwa573** [wallabag/android-app#1136]
Whenever I try to "sweep" deleted article, I get an error notification which says:

> wallabag · Unknown error
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
Stacktrace:
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:148)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at wallabag.apiwrapper.TokenRefreshingInterceptor.intercept(TokenRefreshingInterceptor.java:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.articlesExistByHashes(WallabagService.java:536)
	at wallabag.apiwrapper.BatchExistQueryBuilder.execute(BatchExistQueryBuilder.java:270)
	at fr.gaulupeau.apps.Poche.service.workers.DeletedArticleSweeper.performSweep(DeletedArticleSweeper.java:215)
	at fr.gaulupeau.apps.Poche.service.workers.DeletedArticleSweeper.sweepDeletedArticles(DeletedArticleSweeper.java:79)
	at fr.gaulupeau.apps.Poche.service.workers.DeletedArticleSweeper.sweep(DeletedArticleSweeper.java:56)
	at fr.gaulupeau.apps.Poche.service.tasks.SweepDeletedArticlesTask.run(SweepDeletedArticlesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(lambda)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(TaskService.java)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(lambda)
	at java.lang.Thread.run(Thread.java:818)
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
		... 32 more

# Environment details
- **wallabag app version**: 2.4.2 (228)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Google Play store
- **Android OS version**: 6.0.1
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: Nexus 7
- **wallabag server version**: wallabag.it

Other than that, the Android app is great; thanks very much for this project!

**Comment by di72nn** [comment]
Probably the same as #909. We haven't been able to find the cause of the issue yet.
