### ISSUE TITLE
while image downloading: java.io.InterruptedIOException: interrupted

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#1171]
# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes/

### Actual behaviour

```
2021-06-15 00:29:14.878 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/ImageCacheUtils: cacheImages: downloading /assets/images/6/1/61948288/8320454d.jpeg
2021-06-15 00:29:14.878 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/ImageCacheUtils: getCacheImageName: imageURL=/assets/images/6/1/61948288/8320454d.jpeg
2021-06-15 00:29:14.878 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/ImageCacheUtils: getCacheImageName: localImageName=bc51cca42d8c5f6bb818eb467e7251d3.jpeg for URL /assets/images/6/1/61948288/8320454d.jpeg
2021-06-15 00:29:14.878 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/ImageCacheUtils: getCacheImagePath: localImageName=bc51cca42d8c5f6bb818eb467e7251d3.jpeg for URL /assets/images/6/1/61948288/8320454d.jpeg
2021-06-15 00:29:14.878 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/ImageCacheUtils: getCacheImagePath: localImagePath=/storage/emulated/0/Android/data/fr.gaulupeau.apps.InThePoche.debug/files/imagecache/2110/bc51cca42d8c5f6bb818eb467e7251d3.jpeg
2021-06-15 00:29:14.878 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/ImageCacheUtils: cacheImages: found wallabag relative path: /assets/images/6/1/61948288/8320454d.jpeg
2021-06-15 00:29:14.878 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/ImageCacheUtils: downloadImageToCache: imageURL=https://mywallabag.de/assets/images/6/1/61948288/8320454d.jpeg destination=/storage/emulated/0/Android/data/fr.gaulupeau.apps.InThePoche.debug/files/imagecache/2110/bc51cca42d8c5f6bb818eb467e7251d3.jpeg
2021-06-15 00:29:14.879 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/OkHttp: Sending request https://mywallabag.de/assets/images/6/1/61948288/8320454d.jpeg on null
2021-06-15 00:29:14.960 27284-27640/fr.gaulupeau.apps.InThePoche.debug D/ImageCacheUtils: IOException while requesting imageURL=https://mywallabag.de/assets/images/6/1/61948288/8320454d.jpeg in articleID=2110
    java.io.InterruptedIOException: interrupted
        at okio.Timeout.throwIfReached(Timeout.kt:98)
        at okio.OutputStreamSink.write(JvmOkio.kt:50)
        at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
        at okio.RealBufferedSink.flush(RealBufferedSink.kt:267)
        at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.kt:155)
        at okhttp3.internal.connection.Exchange.finishRequest(Exchange.kt:91)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at fr.gaulupeau.apps.Poche.network.WallabagConnection$LoggingInterceptor.intercept(WallabagConnection.java:178)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at fr.gaulupeau.apps.Poche.network.ImageCacheUtils.downloadImageToCache(ImageCacheUtils.java:297)
        at fr.gaulupeau.apps.Poche.network.ImageCacheUtils.cacheImages(ImageCacheUtils.java:208)
        at fr.gaulupeau.apps.Poche.service.workers.ArticleImagesFetcher.fetchImages(ArticleImagesFetcher.java:121)
        at fr.gaulupeau.apps.Poche.service.workers.ArticleImagesFetcher.fetch(ArticleImagesFetcher.java:45)
        at fr.gaulupeau.apps.Poche.service.tasks.FetchArticleImagesTask.run(FetchArticleImagesTask.java:17)
        at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
        at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
        at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
        at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
        at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:919)
```

### Expected behaviour
- Tell us what should happen
No error and download shall succeed

# Steps to reproduce the issue
1. i re-setup my debug app version
2. enabled image caching
3. download articles and images

# Environment details
- **wallabag app version**: master branch commit d94f35d6745e5707dd4accdc7a99a94bb3f771df
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): manual
- **Android OS version**: 11
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: Samsung S9
- **wallabag server version**: 2.4.2
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
Please paste relevant wallabag server logs here (from file `<wallabag>/var/logs/prod.log`):
-

## Web server
Please paste relevant web server logs (e.g. from nginx, Apache, …) here:
-

**Comment by di72nn** [comment]
Likely caused by background restrictions. #974.
