### ISSUE TITLE
Can't connect to self-hosted wallabag instance

### ISSUE THREAD

**Issue by putzwasser** [wallabag/android-app#1226]
# Issue details
I can't connect to my self-hosted wallabag instance. Everyting seems to be properly set up.
I entered the login info in the settings and the app fetched the api data by itself.
The connection test, which runs automatically yielded no error, but I can't sync my stored articles.

### Duplicate?
Have you searched the issues of this repository if your issue is already known?
yes, not an duplicate

### Actual behaviour
I get the error messge which is included below

### Expected behaviour
Sync the stored articles

# Steps to reproduce the issue
1. Open app
2. Set up sync
3. Sync

# Environment details
- **wallabag app version**: 2.4.3 (229)
- **wallabag app installation source**  Gplay
- **Android OS version**: Android 10
- **Android ROM** stock
- **Android hardware**: 
- **wallabag server version**: 2.4.2
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## wallabag server
```
Serverfehler
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
		at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
			at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
				at wallabag.apiwrapper.WallabagService.lambda$getArticles$0$WallabagService(WallabagService.java:218)
					at wallabag.apiwrapper.-$$Lambda$WallabagService$PrzoUvX9wnRBX2jTxVqPJ-eD3zU.run(Unknown Source:4)
						at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
							at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
								at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
									at wallabag.apiwrapper.WallabagService.getArticles(WallabagService.java:218)
										at wallabag.apiwrapper.ArticlesQueryBuilder.execute(ArticlesQueryBuilder.java:282)
											at wallabag.apiwrapper.ArticlesPageIterator.hasNext(ArticlesPageIterator.java:80)
												at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:183)
													at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
														at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
															at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
																at fr.gaulupeau.apps.Poche.service.tasks.UpdateArticlesTask.run(UpdateArticlesTask.java:17)
																	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
																		at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
																			at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
																				at 
Plfr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
																					at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
																						at java.lang.Thread.run(Thread.java:919)
																						
```

```
$ cat var/logs/prod.log 
[2021-12-09 16:50:53] request.INFO: Matched route "api_get_entries". {"route":"api_get_entries","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\EntryRestController::getEntriesAction","_format":"json","_route":"api_get_entries"},"request_uri":"https://wb.****.de/api/entries.json?detail=full&order=asc&page=1&perPage=30&since=0&sort=updated","method":"GET"} []
[2021-12-09 16:50:53] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getType" of class "ReflectionProperty"." at /www/htdocs/****/wallabag/vendor/jms/serializer/src/Metadata/Driver/TypedPropertiesDriver.php line 107 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getType\" of class \"ReflectionProperty\". at /www/htdocs/****/wallabag/vendor/jms/serializer/src/Metadata/Driver/TypedPropertiesDriver.php:107)"} []
```

The browser extensions runs fine, so I guess it's not a server problem.

**Comment by di72nn** [comment]
Hi!

> The browser extensions runs fine, so I guess it's not a server problem.

The browser extension probably doesn't need this particular API method (at least with similar parameters).

This is clearly a server-side problem. My first guess is incompatible PHP version, but I'm not very knowledgeable about PHP.
Google provides a couple of matches by this query: `Attempted to call an undefined method named "getType" of class "ReflectionProperty"`.

**Comment by putzwasser** [comment]
> My first guess is incompatible PHP version

That's it. It was 7.3. Switchted to 7.4. and it runs smoothly.

I hope I don't run into other problems because of switching to 7.4, because the documentation says 7.4 isn't recommended. . .

**Comment by Strubbl** [comment]
> I hope I don't run into other problems because of switching to 7.4, because the documentation says 7.4 isn't recommended. . .

Maybe you can improve the documentation in this regard?

**Comment by di72nn** [comment]
> I hope I don't run into other problems because of switching to 7.4, because the documentation says 7.4 isn't recommended. . .

It's fine, wallabag supports 7.4 since [2.4.0](https://github.com/wallabag/wallabag/releases/tag/2.4.0). The docs seem to be outdated.

> Maybe you can improve the documentation in this regard?

Well, I don't think @putzwasser possesses the information required to do so :)
But feel free to contribute the correction if you have the time to figure it out.
