### ISSUE TITLE
Can't pull posts

### ISSUE THREAD

**Issue by Tealk** [wallabag/android-app#1243]
Hello,

I have my own Wallabag instance and I can add it to the app and it connects as well. But when I want to fetch the posts I get the following error message:

```
Serverfehler
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.lambda$getArticles$0$WallabagService(WallabagService.java:218)
	at wallabag.apiwrapper.-$$Lambda$WallabagService$PrzoUvX9wnRBX2jTxVqPJ-eD3zU.run(Unknown Source:4)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
	at wallabag.apiwrapper.WallabagService.getArticles(WallabagService.java:218)
	at wallabag.apiwrapper.ArticlesQueryBuilder.execute(ArticlesQueryBuilder.java:282)
	at wallabag.apiwrapper.ArticlesPageIterator.hasNext(ArticlesPageIterator.java:80)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:183)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
	at fr.gaulupeau.apps.Poche.service.tasks.UpdateArticlesTask.run(UpdateArticlesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:920)
```
I have the problem since the update to 2.4.3

Handy: Pixel6 with CalyxOS 
Server: Debian 11, nginx, php7.4-fpm

**Comment by Tealk** [comment]
Have update to php8.1-fpm, now i can pull Posts without problem
