### ISSUE TITLE
500 error from wallabag.it while syncing

### ISSUE THREAD

**Issue by erik-h** [wallabag/android-app#1247]
Hello,

I've come to realize my Wallabag Android app stopped syncing successfully on January 14, 2022. Whenever I try to sync I get the below error. I am using a Wallabag.it subscription for the server. Any help would be greatly appreciated.

# Issue details

### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes/no

Yes - I see other issues relating to HTTP 500 errors, but I am using the https://wallabag.it instance for my server, so I can't debug on the server side.

### Actual behaviour
- When I try to perform a sync on the Android app, I get an exception stating the HTTP 500.

### Expected behaviour
- The app should sync successfully to the wallabag.it server.

# Steps to reproduce the issue
1. Open the Android app
2. Wait for the auto sync to occur, or manually try to start a sync
3. The sync will fail with the below exception

# Environment details
- **wallabag app version**: 2.4.3 (229)
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Gplay
- **Android OS version**: 12
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): stock
- **Android hardware**: Google Pixel 3a XL
- **wallabag server version**: Unsure - I'm connecting to the wallabag.it instance
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## Android stacktrace

```
Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.lambda$modifyArticle$7$WallabagService(WallabagService.java:868)
	at wallabag.apiwrapper.-$$Lambda$WallabagService$zRXhJOiZErB9tSv-KfKfEd87v0w.run(Unknown Source:6)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
	at wallabag.apiwrapper.WallabagService.modifyArticle(WallabagService.java:868)
	at wallabag.apiwrapper.ModifyArticleBuilder.execute(ModifyArticleBuilder.java:103)
	at wallabag.apiwrapper.ModifyArticleBuilder.execute(ModifyArticleBuilder.java:86)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncArticleChange(OfflineChangesSynchronizer.java:368)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.syncOfflineQueue(OfflineChangesSynchronizer.java:118)
	at fr.gaulupeau.apps.Poche.service.workers.OfflineChangesSynchronizer.synchronize(OfflineChangesSynchronizer.java:68)
	at fr.gaulupeau.apps.Poche.service.tasks.SyncOfflineChangesTask.run(SyncOfflineChangesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:920)
```

# Your experience with wallabag Android app
Have you had any luck using wallabag Android app before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

I like the app a lot! I've been using it daily for 3 years now.

**Comment by Strubbl** [comment]
It would have been nice, if you would have given more information as requested in the template. 
The app is reporting an http error 500. That means something with your wallabag server instance is wrong.

**Comment by erik-h** [comment]
Ah sorry about not using the template - I created the issue on GitHub mobile and the template didn't automatically populate for some reason. I'll edit my original comment.

Regarding the server instance having something wrong: I'm using https://wallabag.it as my server, not hosting my own.

**Comment by Strubbl** [comment]
Thanks for giving some more info. Maybe @nicosomb can help here?

**Comment by nicosomb** [comment]
@erik-h could you send me a mail with your wallabag account please?

**Comment by erik-h** [comment]
Thanks @Strubbl.


@nicosomb sounds good, I'll send you an email.

**Comment by nicosomb** [comment]
Hmm, your account seems ok. 

@Strubbl do you think that I can provide you more details?

**Comment by erik-h** [comment]
@nicosomb @Strubbl an update: I've re-installed the app and that seems to have fixed whatever the problem was. Interesting haha. I guess I probably should have tried that sooner!

I guess that means the issue's resolved from my perspective, at least for now. Perhaps we can close this issue and I'll re-open it if the problem continues to occur?

**Comment by Strubbl** [comment]
Thank you very much for reporting back. I would have had no further idea for the cause. Yes, we can proceed as you suggested.

**Comment by erik-h** [comment]
Sounds good. Thanks @Strubbl @nicosomb!
