### ISSUE TITLE
Upgrading to Wallabag 2.4.3 broke the app 

### ISSUE THREAD

**Issue by gerroon** [wallabag/android-app#1261]
Hi

I upgraded my Wallabag from 2.4.2 and 2.4.3 and the app started having problems and throws these exceptions/

I host Wallabag with Apache and Mysql  on Debian testing. I use the 2.4.3 version of the app on Android 18.1.  This was working fine in Wallabag 2.4.2

```
Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error
	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
	at wallabag.apiwrapper.WallabagService.lambda$getArticles$0$WallabagService(WallabagService.java:218)
	at wallabag.apiwrapper.-$$Lambda$WallabagService$PrzoUvX9wnRBX2jTxVqPJ-eD3zU.run(Unknown Source:4)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
	at wallabag.apiwrapper.WallabagService.getArticles(WallabagService.java:218)
	at wallabag.apiwrapper.ArticlesQueryBuilder.execute(ArticlesQueryBuilder.java:282)
	at wallabag.apiwrapper.ArticlesPageIterator.hasNext(ArticlesPageIterator.java:80)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:183)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
	at fr.gaulupeau.apps.Poche.service.tasks.UpdateArticlesTask.run(UpdateArticlesTask.java:17)
	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by di72nn** [comment]
You should check server logs - an `Internal Server Error` occurs when the app is simply trying to load articles via API.

**Comment by gerroon** [comment]
> You should check server logs - an `Internal Server Error` occurs when the app is simply trying to load articles via API.

Thanks but why would it start doing it suddenly? The web app works, and I have not anything else on the server between the versions?

**Comment by di72nn** [comment]
Hard to say. Some data may cause errors on the API, but not on the web UI. Maybe the updated version handles something differently, maybe it's just a coincidence.
It should be clear(er) after checking the logs.

**Comment by njean42** [comment]
Hey there.
I had the same issue of the android app getting a 500 when trying to perform a quick sync. Also started out of the blue.

What I did:
1. check the logs: nothing apart from an access log line: `44.33.22.11 - - [27/May/2022:09:57:27 +0200] "GET /api/entries.json?perPage=30&page=1&sort=updated&detail=full&order=asc&since=1653464118 HTTP/1.1" 500 5538 "-" "okhttp/4.9.1"`
2. try a complete sync: worked for all pages, except the last/latest one: `44.33.22.11 - - [27/May/2022:10:04:12 +0200] "GET /api/entries.json?perPage=30&page=163&sort=created&detail=full&order=asc&since=0 HTTP/1.1" 500 5538 "-" "okhttp/4.9.1"`
3. copy-paste the (15) latest article URLs, up to the latest sync'ed one in the app
4. delete these 15 latest articles: android app sync is working again
5. add articles one by one, sync the android app each time
Conclusion: android app is syncing again, the issue vanished...
Probably was an issue with some article's content, but I'm not able to tell which, since it fixed itself.

@gerroon: maybe you can try this out if it's not too many articles?

My config in case it could help:
- debian 11.2
- apache 2.4.53-1~deb11u1
- php 7.4.25
- wallabag 2.4.0
- sqlite db

**Comment by gerroon** [comment]
@njean42  I had that issue before and I was able to get the app back by removing last article however in this case between the upgrades there were not any new articles, so in my view that would not be an article related issue, given the app started freaking out aftert the upgrade.

**Comment by njean42** [comment]
> makes sense indeed

**Comment by Micha-Btz** [comment]
did you solve the error? I have problemms too, but seems a different error:

> Unbekannter Fehler
> wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 403 
> Stacktrace:
> wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 403 
> 	at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
> 	at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
> 	at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
> 	at wallabag.apiwrapper.WallabagService.lambda$getArticles$0$WallabagService(WallabagService.java:218)
> 	at wallabag.apiwrapper.-$$Lambda$WallabagService$PrzoUvX9wnRBX2jTxVqPJ-eD3zU.run(Unknown Source:4)
> 	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
> 	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
> 	at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
> 	at wallabag.apiwrapper.WallabagService.getArticles(WallabagService.java:218)
> 	at wallabag.apiwrapper.ArticlesQueryBuilder.execute(ArticlesQueryBuilder.java:282)
> 	at wallabag.apiwrapper.ArticlesPageIterator.hasNext(ArticlesPageIterator.java:80)
> 	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:183)
> 	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
> 	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
> 	at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
> 	at fr.gaulupeau.apps.Poche.service.tasks.UpdateArticlesTask.run(UpdateArticlesTask.java:17)
> 	at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
> 	at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
> 	at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
> 	at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
> 	at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
> 	at java.lang.Thread.run(Thread.java:920)

Web pages work fine, first seem after the upgrade.
Any Ideas?
TIA Micha

**Comment by gerroon** [comment]
I was not able to solve it. I just stopped using the app.

**Comment by di72nn** [comment]
@Micha-Btz I would suggest to start with re-running the connection wizard, because the error you get seems to be related to authentication.

@gerroon so you didn't find anything useful in the server logs?

**Comment by Micha-Btz** [comment]
@di72nn re-running the connection wizard solved the issue for me. Thanks.

**Comment by thiswillbeyourgithub** [comment]
Well F###.

It appears running the connection wizard will not only re authenticate but will also wipe your local database. This if very frustrating as I lost a few days of reading and some articles I will never remember about :(

The issue had been happenning to me for about a week (?) on the official app.wallabag.it.
