### ISSUE TITLE
Problem with OFFLINE_URL table constraint

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#155]
Seems like urls stored in OFFLINE_URL are not unique.

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: OFFLINE_URL.url (code 2067)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:812)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at de.greenrobot.dao.AbstractDao.executeInsert(AbstractDao.java:348)
	at de.greenrobot.dao.AbstractDao.insert(AbstractDao.java:293)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.doInBackground(AddLinkTask.java:80)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.doInBackground(AddLinkTask.java:22)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by di72nn** [comment]
I don't see it reproduce. New stacktrace?

**Comment by tcitworld** [comment]
Oops, sorry, I guessed I misclicked.
