### ISSUE TITLE
GPlay bug report IllegalArgumentException: the bind value at index 1 is null

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#175]
Seems to be a Null exception again.
```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:200)
	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
	at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null
	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:237)
	at android.database.sqlite.SQLiteQuery.bindString(SQLiteQuery.java:185)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:48)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1358)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1326)
	at de.greenrobot.dao.query.Query.unique(Query.java:170)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.processFeed(UpdateFeedTask.java:247)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateByFeed(UpdateFeedTask.java:169)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateAllFeeds(UpdateFeedTask.java:103)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:67)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:30)
	at android.os.AsyncTask$2.call(AsyncTask.java:185)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
	... 4 more
```

**Comment by di72nn** [comment]
We use `<source url="https://wallabag.example.com/?view=view&id=123456" >wallabag</source>` tag from feed to get server-side id of an article. In this case the id for some reason wasn't found (either the tag is missing or it doesn't have `&id=123456` part).

I can fix that exception, but those ids are essential to perform any client->server actions (except URL uploading). Making it optional also requires to make `article_id` non-unique.

That all is doable, but I'm not sure it's a common problem. The user is probably using very old server (older than [this commit](https://github.com/wallabag/wallabag/commit/f86784c22d63ebd8315d0f86befa626779e36ff3)), which should be fixed on his side.

I guess I should only add "feed format is unsupported" error message.

**Comment by tcitworld** [comment]
It's quite odd, though, since there's been already two bug reports (on different devices) like this. I'll wait to see if there's more like this to come.

Also, please note that both bug reports concern *Android 2.3.3 - 2.3.7* versions.

> I guess I should only add "feed format is unsupported" error message.

Instead of such a message, could the article item in the feed just be ignored (with eventually a message at the end of sync saying that one did failed) ?

**Comment by di72nn** [comment]
Turns out [Android ~2.3.3 has a bug in xmp parser](http://android-developers.blogspot.ru/2011/12/watch-out-for-xmlpullparsernexttext.html). Thanks for mentioning Android versions, I probably wouldn't find it otherwise.

**Comment by Strubbl** [comment]
This issue occured again, this time on a more recent device:

App-Version
    24
    23

Android-Version
    Android 5.12

Gerät
    Moto G with 4G LTE (1st Gen) (peregrine)

the reported exception:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null
	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
	at de.greenrobot.dao.query.Query.unique(Query.java:170)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.processFeed(UpdateFeedTask.java:306)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateByFeed(UpdateFeedTask.java:190)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateAllFeeds(UpdateFeedTask.java:112)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:71)
	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:30)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

user comment: Plante à la tentative de chargement
