### ISSUE TITLE
Completely fail to sync on Android 4.1

### ISSUE THREAD

**Issue by azrdev** [wallabag/android-app#176]
I've installed wallabag through f-droid, and recently updated to 1.9.3.1
Since, the app never succeeds to fetch the feed from my self-hosted server (1.9.1).

logcat:
~~~
12-17 20:49:55.025 E/SpannableStringBuilder(10030): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
12-17 20:49:55.025 E/SpannableStringBuilder(10030): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
12-17 20:50:23.104 W/dalvikvm(10030): VFY: unable to find class referenced in signature (Ljava/nio/file/Path;)
12-17 20:50:23.104 W/dalvikvm(10030): VFY: unable to find class referenced in signature ([Ljava/nio/file/OpenOption;)
12-17 20:50:23.104 I/dalvikvm(10030): Could not find method java.nio.file.Files.newOutputStream, referenced from method okio.Okio.sink
12-17 20:50:23.104 W/dalvikvm(10030): VFY: unable to resolve static method 24147: Ljava/nio/file/Files;.newOutputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/OutputStream;
12-17 20:50:23.104 W/dalvikvm(10030): VFY: unable to find class referenced in signature (Ljava/nio/file/Path;)
12-17 20:50:23.104 W/dalvikvm(10030): VFY: unable to find class referenced in signature ([Ljava/nio/file/OpenOption;)
12-17 20:50:23.104 I/dalvikvm(10030): Could not find method java.nio.file.Files.newInputStream, referenced from method okio.Okio.source
12-17 20:50:23.104 W/dalvikvm(10030): VFY: unable to resolve static method 24146: Ljava/nio/file/Files;.newInputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/InputStream;
12-17 20:50:23.704 I/AppCompatDelegate(10030): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
12-17 20:52:36.084 I/AppCompatDelegate(10030): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
12-17 20:52:41.264 I/AppCompatDelegate(10030): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
12-17 20:52:47.514 I/dalvikvm-heap(10030): Grow heap (frag case) to 12.446MB for 249110-byte allocation
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): IOException on Archive
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): java.io.InterruptedIOException: thread interrupted
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at okio.Timeout.throwIfReached(Timeout.java:145)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at okio.Okio$2.read(Okio.java:136)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at com.squareup.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:464)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at java.io.InputStreamReader.read(InputStreamReader.java:244)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1496)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1340)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:390)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:310)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at org.kxml2.io.KXmlParser.nextText(KXmlParser.java:2056)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.parseItem(UpdateFeedTask.java:353)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.processFeed(UpdateFeedTask.java:241)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateByFeed(UpdateFeedTask.java:169)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.updateAllFeeds(UpdateFeedTask.java:107)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:67)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at fr.gaulupeau.apps.Poche.network.tasks.UpdateFeedTask.doInBackground(UpdateFeedTask.java:30)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
12-17 20:52:55.704 E/FeedUpdater.updateByF(10030): 	at java.lang.Thread.run(Thread.java:856)
~~~

**Comment by di72nn** [comment]
I'm not sure if it's relevant, but how many articles do you have (rough; unread, archived and favorites separate)?

**Comment by azrdev** [comment]
unread 35
favorites 0
archive 308
tags 1

**Comment by di72nn** [comment]
That exception is thrown if update process is interrupted (screen orientation change, the app gets into background, screen is off, etc.).
Unfortunately, current implementation requires the update to be performed uninterrupted for the whole time of the process. It's probably tedious in case of your "archive" feed, but there is nothing can be done right now (until we move to using background services for updates).
Anyway, you may get only unread articles with "pull-to-refresh" action on "Unread" feed. It should be quite fast. You may update other feeds that way (one by one), but your "archive" feed will take the most time.

In case that you tried to wait more that a couple of minutes (from my experience, full update for ~500 articles takes less than a minute, but it depends on many factors), we have to investigate it further.
I updated a library we use for network requests and added some more logging. That will be available with the next app update.

**Comment by azrdev** [comment]
Indeed, when only configuring the token (no username/pw), and doing pull-to-refresh (which I didn't know about before) without any interruption, the *unread* feed syncs successfully and quite fast.

However, to tell the server that an article was read, I need username/pw, right? The archive is not important to me, atm.

**Comment by di72nn** [comment]
Presence of username and password should not affect feed updates.
Username and password are required to perform any client->server sync (changing article state and adding new urls to wallabag via the app). If username/pw are not entered, all changes will be available only locally in the app.

**Comment by di72nn** [comment]
Noted down as #181.
