### ISSUE TITLE
SQLiteConstraintException: UNIQUE constraint failed: ARTICLE.article_id

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#186]
User feedback from Google Play :

> spamming archive on a heap of links then clicking refresh

```
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: ARTICLE.article_id (code 2067)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:725)
	at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
	at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
	at de.greenrobot.dao.AbstractDao.updateInsideSynchronized(AbstractDao.java:679)
	at de.greenrobot.dao.AbstractDao.update(AbstractDao.java:654)
	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:42)
	at fr.gaulupeau.apps.Poche.network.tasks.ToggleArchiveTask.onPostExecute(ToggleArchiveTask.java:13)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5832)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by di72nn** [comment]
Probably caused by concurrent execution of multiple async operations on the same article. In that case, instead of fixing it, I'd prefer to implement #181, which should eliminate this issue. Unfortunately, I don't have estimates when I'll be able to get to #181.

**Comment by tcitworld** [comment]
Agreed.

**Comment by di72nn** [comment]
Obsolete.
