### ISSUE TITLE
Error uploading links stored off-line

### ISSUE THREAD

**Issue by khinsen** [wallabag/android-app#197]
I share links to Wallabag often when I don't have a network connection, and then I upload them later. Today this failed - without any further explanation. I had two links stored off-line, and apparently uploading the first one failed. It looks like uploading the second one was not even attempted.

A bit later I added another link off-line. Now I have three links to upload, but since the first one fails, I am stuck. Worse, it looks like all further links I will store off-line will be lost, because I cannot upload them.

Conclusions:
1. If an upload fails, the remaining off-line links should be uploaded nevertheless.
2. It would be nice to know _why_ a link upload failed.
3. It would be nice to be able to remove the offending link, to restore normal operation.

Tested with Wallabag for Android version 1.9.3 and a Framabag account.

**Comment by di72nn** [comment]
If you installed the app from Google Play, you may use [an apk](https://github.com/wallabag/android-app/issues/193#issuecomment-179387049) as a workaround to upload links independently and to extract problem links.

Can you provide the link that caused the problem?

**Comment by khinsen** [comment]
Thanks for the pointer!

With the new app, two of my three links are copied to the clipboard as "failed", but all three end up in my Wallabag! That makes me wonder what the failure consists of.

Here are the two links on the clipboard:

  http://laviedemix.over-blog.com/2016/02/remaniement.html
  http://laviedemix.over-blog.com/2016/02/faire-chier-le-monde-un-exemple-l-autorisation-de-cumul.html

**Comment by di72nn** [comment]
Thank you for the links.

I don't experience the problem with self-hosted Wallabag instance, but with Framabag the app throws the following exceptions for unknown reason. The exceptions was thrown after about 13 seconds (not really timed out?).

On Android 4.2.2:
`
java.net.SocketTimeoutException: Read timed out
    at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:664)
    at okio.Okio$2.read(Okio.java:139)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
    at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
    at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
    at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
    at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:92)
    at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:891)
    at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:749)
    at com.squareup.okhttp.Call.getResponse(Call.java:268)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
    at com.squareup.okhttp.Call.execute(Call.java:79)
    at fr.gaulupeau.apps.Poche.network.WallabagService.exec(WallabagService.java:248)
    at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequestForResult(WallabagService.java:222)
    at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequest(WallabagService.java:211)
    at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequest(WallabagService.java:207)
    at fr.gaulupeau.apps.Poche.network.WallabagService.addLink(WallabagService.java:88)
    at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.doInBackground(AddLinkTask.java:69)
    at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.doInBackground(AddLinkTask.java:22)
    at android.os.AsyncTask$2.call(AsyncTask.java:287)
    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
    at java.lang.Thread.run(Thread.java:856)
`

On Android 4.4.4:
`D/OkHttp: Sending request https://framabag.org/u/username?plainurl=http://laviedemix.over-blog.com/2016/02/remaniement.html on null
java.net.SocketTimeoutException: timeout
    at okio.Okio$3.newTimeoutException(Okio.java:207)
    at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
    at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
    at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
    at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:739)
    at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
    at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:724)
    at com.facebook.stetho.okhttp.StethoInterceptor.intercept(StethoInterceptor.java:58)
    at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:697)
    at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:578)
    at com.squareup.okhttp.Call.getResponse(Call.java:287)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
    at fr.gaulupeau.apps.Poche.network.WallabagConnection$LoggingInterceptor.intercept(WallabagConnection.java:166)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
    at com.squareup.okhttp.Call.execute(Call.java:80)
    at fr.gaulupeau.apps.Poche.network.WallabagService.exec(WallabagService.java:248)
    at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequestForResult(WallabagService.java:222)
    at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequest(WallabagService.java:211)
    at fr.gaulupeau.apps.Poche.network.WallabagService.executeRequest(WallabagService.java:207)
    at fr.gaulupeau.apps.Poche.network.WallabagService.addLink(WallabagService.java:88)
    at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.doInBackground(AddLinkTask.java:69)
    at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.doInBackground(AddLinkTask.java:22)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)`

Other requests (log in, etc.) seems to work fine.

I'll try to investigate it later.

**Comment by di72nn** [comment]
On second thought, it really may be caused by low read timeout. Didn't expect default value so low.

**Comment by kai11** [comment]
@di72nn Please upload version with updated timeout to f-droid.
PS. I'm personally fine with hardcoded 30 seconds.

**Comment by di72nn** [comment]
#307.
