### ISSUE TITLE
App doesn't start.

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#200]
A friend has a Wiko phone running Android 4.2.2. 
He is affected by [this](https://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder) issue and the app doesn't start.

The error is `NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder`.

Also, log from GPlay :

```
java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
    at android.support.v7.app.AppCompatDelegateImplV7.initializePanelMenu(AppCompatDelegateImplV7.java:1194)
    at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1258)
    at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1553)
    at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
    at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:129)
    at android.os.Handler.handleCallback(Handler.java:800)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5391)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Strubbl** [comment]
Which app version is he using?

**Comment by tcitworld** [comment]
Will have an update.

**Comment by di72nn** [comment]
Some info: https://code.google.com/p/android/issues/detail?id=78377#c374

It might be fixed (worked around) in the support library.

Reopen the issue if you get an update.
