### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void android.support.v4.media.session.MediaSessionCompat.setPlaybackState(android.support.v4.media.session.PlaybackStateCompat)' on a null object reference

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#234]
I checked the box "TTS" in an article view and now i cannot open any article anymore - i have to reinstall the app to make the app usuable again. Everytime on every article i open, i get a nullpointer:

```
05-03 17:08:14.109 11885-11885/fr.gaulupeau.apps.InThePoche E/AndroidRuntime: FATAL EXCEPTION: main
      Process: fr.gaulupeau.apps.InThePoche, PID: 11885
      java.lang.RuntimeException: Unable to create service fr.gaulupeau.apps.Poche.tts.TtsService: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.media.session.MediaSessionCompat.setPlaybackState(android.support.v4.media.session.PlaybackStateCompat)' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2771)
       at android.app.ActivityThread.access$1800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.media.session.MediaSessionCompat.setPlaybackState(android.support.v4.media.session.PlaybackStateCompat)' on a null object reference
       at fr.gaulupeau.apps.Poche.tts.TtsService.setMediaSessionPlaybackState(TtsService.java:719)
       at fr.gaulupeau.apps.Poche.tts.TtsService.onInit(TtsService.java:531)
       at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
       at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:792)
       at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:723)
       at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:702)
       at fr.gaulupeau.apps.Poche.tts.TtsService.onCreate(TtsService.java:163)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2761)
       at android.app.ActivityThread.access$1800(ActivityThread.java:151) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:135) 
       at android.app.ActivityThread.main(ActivityThread.java:5254) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

@tyndare Maybe you have an idea?

**Comment by tyndare** [comment]
I may have found the issue.
Are you able to check that this commit fix it ?
https://github.com/tyndare/android-app/commit/0fd00db45d04ae1475d77a5d1cd69c5db8177426
I created a new branch for it:
https://github.com/tyndare/android-app/tree/tts-fix-issue-234

**Comment by Strubbl** [comment]
Yes, the null pointer when opening articles is fixed with this commit. I experienced two new issues, i am going to report. Maybe you can have a look at them also?

**Comment by di72nn** [comment]
Seems to be fixed.
