### ISSUE TITLE
TtsFragment.onPause causes RuntimeException: Unable to pause activity {ReadArticleActivity}: IllegalArgumentException: setShowActionsInCompactView: action 0 out of bounds (max -1)

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#237]
Steps to repoduce:

1. fresh new install of tyndare@0fd00db branch https://github.com/tyndare/android-app/tree/tts-fix-issue-234
2. start app, enter wallabag data & save settings
3. synchronize
4. open first article in list
5. click on article settings and check the box for TTS
6. now hit the Back button of your smartphone
7. crash, see following stack trace

OR

you can reproduce this issue with the following steps, too:

1. open article
2. open settings and check the box for TTS
3. open settings again and uncheck the box for TTS
4. same exception for crash, see following log

```
05-03 22:13:22.268 15720-15720/fr.gaulupeau.apps.InThePoche D/ReadArticleActivity: onPageFinished() calling loadingFinished()
05-03 22:13:22.268 15720-15720/fr.gaulupeau.apps.InThePoche D/ReadArticle.restorePos: positionToRestore: null
05-03 22:13:26.126 15720-15720/fr.gaulupeau.apps.InThePoche D/WebviewText: parseWebviewDocument
05-03 22:13:26.169 15720-15720/fr.gaulupeau.apps.InThePoche D/TtsFragment: loadTtsEnginesList
05-03 22:13:26.172 15720-15720/fr.gaulupeau.apps.InThePoche D/TtsFragment: onCreateView
05-03 22:13:26.343 15720-15720/fr.gaulupeau.apps.InThePoche D/WebviewText: onDocumentParseEnd
05-03 22:13:26.387 15720-15720/fr.gaulupeau.apps.InThePoche D/TtsService: onCreate
05-03 22:13:26.423 15720-15720/fr.gaulupeau.apps.InThePoche E/MediaPlayer: Should have subtitle controller already set
05-03 22:13:26.456 15720-15720/fr.gaulupeau.apps.InThePoche D/TtsService: TextToSpeech.OnInitListener.onInit -1
05-03 22:13:26.470 15720-15720/fr.gaulupeau.apps.InThePoche D/TtsService: onStartCommand
05-03 22:13:26.471 15720-15720/fr.gaulupeau.apps.InThePoche D/TtsService: playCmd
05-03 22:13:26.474 15720-15720/fr.gaulupeau.apps.InThePoche E/MediaPlayer: Should have subtitle controller already set
05-03 22:13:26.475 15720-15720/fr.gaulupeau.apps.InThePoche D/TtsFragment: onServiceConnected
05-03 22:13:51.212 15720-15720/fr.gaulupeau.apps.InThePoche D/AndroidRuntime: Shutting down VM
      
      
      --------- beginning of crash
05-03 22:13:51.216 15720-15720/fr.gaulupeau.apps.InThePoche E/AndroidRuntime: FATAL EXCEPTION: main
      Process: fr.gaulupeau.apps.InThePoche, PID: 15720
      java.lang.RuntimeException: Unable to pause activity {fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.ReadArticleActivity}: java.lang.IllegalArgumentException: setShowActionsInCompactView: action 0 out of bounds (max -1)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3260)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3219)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3194)
       at android.app.ActivityThread.access$1000(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
       Caused by: java.lang.IllegalArgumentException: setShowActionsInCompactView: action 0 out of bounds (max -1)
       at android.app.Notification$MediaStyle.makeMediaContentView(Notification.java:4268)
       at android.app.Notification$MediaStyle.populateContentView(Notification.java:4202)
       at android.app.Notification$Style.buildStyled(Notification.java:3669)
       at android.app.Notification$MediaStyle.buildStyled(Notification.java:4190)
       at android.app.Notification$Builder.build(Notification.java:3477)
       at android.support.v4.app.NotificationCompatApi21$Builder.build(NotificationCompatApi21.java:120)
       at android.support.v7.app.NotificationCompat$LollipopExtender.build(NotificationCompat.java:123)
       at android.support.v4.app.NotificationCompat$NotificationCompatImplApi21.build(NotificationCompat.java:768)
       at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:1559)
       at fr.gaulupeau.apps.Poche.tts.TtsService.generateNotification(TtsService.java:776)
       at fr.gaulupeau.apps.Poche.tts.TtsService.setForegroundAndNotification(TtsService.java:741)
       at fr.gaulupeau.apps.Poche.tts.TtsService.setVisible(TtsService.java:645)
       at fr.gaulupeau.apps.Poche.tts.TtsFragment.onPause(TtsFragment.java:478)
       at android.support.v4.app.Fragment.performPause(Fragment.java:2139)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1117)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2060)
       at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:207)
       at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:444)
       at fr.gaulupeau.apps.Poche.ui.ReadArticleActivity.onPause(ReadArticleActivity.java:577)
       at android.app.Activity.performPause(Activity.java:6101)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1310)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3246)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3219) 
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3194) 
       at android.app.ActivityThread.access$1000(ActivityThread.java:151) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:135) 
       at android.app.ActivityThread.main(ActivityThread.java:5254) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

I was about to test https://github.com/wallabag/android-app/issues/234#issuecomment-216627597 provided by @tyndare

**Comment by tyndare** [comment]
Thanks for the report. 
Apparently TextToSpeech initialization failed, and then TtsService State = ERROR, something I never encountered (and never tested...).
I tried to avoid crash in this case, but it won't make TTS works if TextToSpeech initialization has failed...
You may try to change the language/voice so that another TextToSpeech engine is initialized.

**Comment by di72nn** [comment]
@Strubbl can you reproduce it?

**Comment by Strubbl** [comment]
If yes, i am going to reopen it.
