### ISSUE TITLE
RuntimeException: Unable to start service TtsService with null: NullPointerException: Attempt to invoke virtual method 'String android.content.Intent.getAction()' on a null object reference

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#238]
This exception triggers after #237 has already crashed the app. It looks like it wants to restart the app and now crashes with the following exception:

```
05-03 22:27:05.492 28489-28489/fr.gaulupeau.apps.InThePoche D/Atlas: Validating map...
05-03 22:27:05.533 28489-28489/fr.gaulupeau.apps.InThePoche D/TtsService: onCreate
05-03 22:27:05.563 28489-28489/fr.gaulupeau.apps.InThePoche E/MediaPlayer: Should have subtitle controller already set
05-03 22:27:05.591 28489-28489/fr.gaulupeau.apps.InThePoche D/TtsService: TextToSpeech.OnInitListener.onInit -1
05-03 22:27:05.603 28489-28489/fr.gaulupeau.apps.InThePoche D/TtsService: onStartCommand
05-03 22:27:05.604 28489-28489/fr.gaulupeau.apps.InThePoche D/AndroidRuntime: Shutting down VM
05-03 22:27:05.605 28489-28489/fr.gaulupeau.apps.InThePoche E/AndroidRuntime: FATAL EXCEPTION: main
      Process: fr.gaulupeau.apps.InThePoche, PID: 28489
      java.lang.RuntimeException: Unable to start service fr.gaulupeau.apps.Poche.tts.TtsService@3347e24e with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
       at android.app.ActivityThread.access$2100(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
       at fr.gaulupeau.apps.Poche.tts.TtsService.onStartCommand(TtsService.java:261)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
       at android.app.ActivityThread.access$2100(ActivityThread.java:151) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:135) 
       at android.app.ActivityThread.main(ActivityThread.java:5254) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
05-03 22:27:21.307 28489-28489/fr.gaulupeau.apps.InThePoche I/Process: Sending signal. PID: 28489 SIG: 9
```

//CC @tyndare

**Comment by tyndare** [comment]
Thanks for the report.
I was not considering the case where the intent could be null.

**Comment by di72nn** [comment]
Probably fixed. Otherwise, feel free to reopen.
