### ISSUE TITLE
NullPointerException causes InflateException: Binary XML file line #4: Error inflating class TextView

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#240]
App-Version
    24

Android-Version
    Android 4.4

Gerät
    Galaxy Note II (t03g)

```
android.view.InflateException: Binary XML file line #4: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.widget.Toast.makeText(Toast.java)
	at android.widget.Toast.makeText(Toast.java)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:97)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:22)
	at android.os.AsyncTask.finish(AsyncTask.java)
	at android.os.AsyncTask.access$600(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.graphics.Rect.set(Rect.java:261)
	at com.android.internal.policy.impl.MultiPhoneWindow.initStackBound(MultiPhoneWindow.java:1142)
	at com.android.internal.policy.impl.MultiPhoneWindow.generateLayout(MultiPhoneWindow.java:424)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3359)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1886)
	at android.support.v7.app.AppCompatDelegateImplV7.shouldInheritContext(AppCompatDelegateImplV7.java:983)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:970)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	... 24 more
```

**Comment by Strubbl** [comment]
This error seems to occur only on Samsung Galaxy Note devices. One user said, he shared an article from Firefox and then the crash happened.

**Comment by di72nn** [comment]
I don't have the latest sources checked out currently, so I had to guess blindly.
If the line 97 in `AddLinkTask.java` is `Toast.makeText(...)` (I can't check until I fetch sources) then the only possible reasons (if it really app's problem) for the error are:
* R.string.addLink_success_text is somehow wrong (not likely),
* the `context` is wrong. `Toast.makeText` should work fine with any (Activity / Application) context, though.

A wild guess: I see presence of `xposed`-framework in the stacktrace and `Error inflating class TextView` (I'm not sure what Toast is, though), so I think it maybe some kind of custom Toast view (via xposed), that can't accept ApplicationContext.

I guess we need more info. Is xposed-framework used on all problem devices? Is the problem always reproducible? Does the stacktrace looks the same on all devices?

**Comment by Strubbl** [comment]
I have three stack traces. No, the xposed stuff is only seen in the stacktrace with app version 24. In app version 23, this cannot be seen, although the device is the same. 

```
android.view.InflateException: Binary XML file line #4: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.widget.Toast.makeText(Toast.java)
	at android.widget.Toast.makeText(Toast.java)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:97)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:22)
	at android.os.AsyncTask.finish(AsyncTask.java)
	at android.os.AsyncTask.access$600(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.graphics.Rect.set(Rect.java:261)
	at com.android.internal.policy.impl.MultiPhoneWindow.initStackBound(MultiPhoneWindow.java:1142)
	at com.android.internal.policy.impl.MultiPhoneWindow.generateLayout(MultiPhoneWindow.java:424)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3359)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1886)
	at android.support.v7.app.AppCompatDelegateImplV7.shouldInheritContext(AppCompatDelegateImplV7.java:983)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:970)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	... 24 more
```

```
android.view.InflateException: Binary XML file line #27: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
	at android.widget.Toast.makeText(Toast.java:291)
	at android.widget.Toast.makeText(Toast.java:322)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:97)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:22)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.graphics.Rect.set(Rect.java:261)
	at com.android.internal.policy.impl.MultiPhoneWindow.initStackBound(MultiPhoneWindow.java:1142)
	at com.android.internal.policy.impl.MultiPhoneWindow.generateLayout(MultiPhoneWindow.java:424)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3359)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1886)
	at android.support.v7.app.AppCompatDelegateImplV7.shouldInheritContext(AppCompatDelegateImplV7.java:983)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:970)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
	... 19 more
```

```
android.view.InflateException: Binary XML file line #27: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
	at android.widget.Toast.makeText(Toast.java:285)
	at android.widget.Toast.makeText(Toast.java:316)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:97)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:22)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5293)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.graphics.Rect.set(Rect.java:261)
	at com.android.internal.policy.impl.MultiPhoneWindow.initStackBound(MultiPhoneWindow.java:820)
	at com.android.internal.policy.impl.MultiPhoneWindow.generateLayout(MultiPhoneWindow.java:256)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3327)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1851)
	at android.support.v7.app.AppCompatDelegateImplV7.shouldInheritContext(AppCompatDelegateImplV7.java:983)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:970)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
	... 19 more
```

**Comment by di72nn** [comment]
That's weird. Couldn't find anything on it yet. I'll try to look more into it as soon as I can.

**Comment by Strubbl** [comment]
Maybe that is a special Samsung Note Android feature. A friend has such a phone. When i see him, i am going to ask if we can test it at his phone. If yes, maybe i get a more verbose log.

**Comment by di72nn** [comment]
@Strubbl can you test #254 on any affected device?

**Comment by Strubbl** [comment]
No, not possible at the moment. The friend having such a phone is in Hungary for some time.

**Comment by di72nn** [comment]
That is most likely fixed. If not, new stack traces should be provided.
