### ISSUE TITLE
ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=lifehac.kr/uCaFxdX }

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#354]
imported from gdev console:

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=lifehac.kr/uCaFxdX }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
	at android.app.Activity.startActivityForResult(Activity.java:4224)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
	at android.app.Activity.startActivityForResult(Activity.java:4183)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
	at android.app.Activity.startActivity(Activity.java:4507)
	at android.app.Activity.startActivity(Activity.java:4475)
	at fr.gaulupeau.apps.Poche.ui.ReadArticleActivity.openOriginal(ReadArticleActivity.java:477)
	at fr.gaulupeau.apps.Poche.ui.ReadArticleActivity.onOptionsItemSelected(ReadArticleActivity.java:574)
	at android.app.Activity.onMenuItemSelected(Activity.java:3204)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:406)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:103)
	at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:667)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3120)
	at android.widget.AbsListView$3.run(AbsListView.java:4035)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

reported one time with Android 7.0 on p4 with app version 28

**Comment by di72nn** [comment]
Most likely the reason is that the URL didn't contain `http://` for some reason. That should not happen. I believe there is an issue about the app not filtering it.

**Comment by di72nn** [comment]
Copied from #568:

```
android.content.ActivityNotFoundException: 
  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
  at android.app.Activity.startActivityForResult(Activity.java:3963)
  at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
  at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
  at android.app.Activity.startActivityForResult(Activity.java:3924)
  at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
  at android.app.Activity.startActivity(Activity.java:4247)
  at android.app.Activity.startActivity(Activity.java:4215)
  at fr.gaulupeau.apps.Poche.ui.ReadArticleActivity$8.onClick(ReadArticleActivity.java:731)
  at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1045)
  at android.widget.AdapterView.performItemClick(AdapterView.java:310)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
  at android.widget.AbsListView$3.run(AbsListView.java:3903)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

https://github.com/wallabag/android-app/blob/2.0.0/app/src/main/java/fr/gaulupeau/apps/Poche/ui/ReadArticleActivity.java#L731


Zeitstempel des Berichts

12. Juni 20:18

App-Version

104

Android-Version

Android 6.0

Gerät
Lenovo TB2-X30F (TB2-X30F)

Hersteller
    Lenovo Mobile
RAM (MB)
    2048
Bildschirmgröße
    1280 × 800
Bildschirmdichte (dpi)
    160
Native Plattform
    armeabi-v7a
OpenGL ES-Version
    3.0
CPU-Marke
    Qualcomm
CPU-Modell
    APQ8009

**Comment by Strubbl** [comment]
This seems to be related with #187
