### ISSUE TITLE
RuntimeException: Unable to instantiate application Poche.App: ClassNotFoundException

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#366]
imported from gplay

```
java.lang.RuntimeException: Unable to instantiate application fr.gaulupeau.apps.Poche.App: java.lang.ClassNotFoundException: Didn't find class "fr.gaulupeau.apps.Poche.App" on path: DexPathList[[zip file "/mnt/asec/fr.gaulupeau.apps.InThePoche-1/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/fr.gaulupeau.apps.InThePoche-1/lib, /vendor/lib, /system/lib]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
	at android.app.ActivityThread.access$1600(ActivityThread.java:164)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5377)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "fr.gaulupeau.apps.Poche.App" on path: DexPathList[[zip file "/mnt/asec/fr.gaulupeau.apps.InThePoche-1/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/fr.gaulupeau.apps.InThePoche-1/lib, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	at android.app.Instrumentation.newApplication(Instrumentation.java:993)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
	... 11 more
	Suppressed: java.io.IOException: unable to open DEX file
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:296)
		at dalvik.system.DexFile.<init>(DexFile.java:80)
		at dalvik.system.DexFile.<init>(DexFile.java:59)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:263)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:230)
		at dalvik.system.DexPathList.<init>(DexPathList.java:112)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:58)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:326)
		at android.app.LoadedApk.makeApplication(LoadedApk.java:508)
		... 11 more
```

 App-Version    29

 Android-Version    Android 4.4

 device    Galaxy Tab Pro 8.4 (mondrianlte)

**Comment by di72nn** [comment]
This is unlikely to be caused by the app.

**Comment by Strubbl** [comment]
Yes, i think that, too. It is reported only one time. Therefore i am going to close this issue until it reoccurs.
