### ISSUE TITLE
IllegalArgumentException View=com.android.internal.policy.PhoneWindow$DecorView not attached to window manager

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#382]
reported on gdev console

```
java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{19d48a3 V.E...... R......D 0,0-1026,348} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:118)
	at android.app.Dialog.dismissDialog(Dialog.java:362)
	at android.app.Dialog.dismiss(Dialog.java:345)
	at fr.gaulupeau.apps.Poche.ui.preferences.ConfigurationTestHelper.onTestConnectionResult(ConfigurationTestHelper.java:142)
	at fr.gaulupeau.apps.Poche.network.tasks.TestConnectionTask.onPostExecute(TestConnectionTask.java:139)
	at fr.gaulupeau.apps.Poche.network.tasks.TestConnectionTask.onPostExecute(TestConnectionTask.java:22)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

reported two times. 
### one time on:

App-Version     
    29

Android-Version     
    Android 6.01

Gerät
    OnePlus One (A0001)

### second time on:

App-Version
    29

Android-Version     
    Android 6.01

Gerät
    Galaxy A5(2016) (a5xelte)

and with a slightly different exception trace:

```
java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{ff44205 V.E...... R......D 0,0-1002,348} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:377)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:140)
	at android.app.Dialog.dismissDialog(Dialog.java:701)
	at android.app.Dialog.dismiss(Dialog.java:684)
	at fr.gaulupeau.apps.Poche.ui.preferences.ConfigurationTestHelper.handleGetCredentialsResult(ConfigurationTestHelper.java:307)
	at fr.gaulupeau.apps.Poche.network.tasks.GetCredentialsTask.onPostExecute(GetCredentialsTask.java:61)
	at fr.gaulupeau.apps.Poche.network.tasks.GetCredentialsTask.onPostExecute(GetCredentialsTask.java:12)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by di72nn** [comment]
Version 226.
Google Pixel 2 XL (taimen), 3840MB RAM, Android 11:
```
java.lang.IllegalArgumentException:
  at android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:544)
  at android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:448)
  at android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:141)
  at android.app.Dialog.dismissDialog (Dialog.java:387)
  at android.app.Dialog.dismiss (Dialog.java:369)
  at fr.gaulupeau.apps.Poche.ui.preferences.ConfigurationTestHelper.dismissDialog (ConfigurationTestHelper.java:394)
  at fr.gaulupeau.apps.Poche.ui.preferences.ConfigurationTestHelper.onTestConnectionResult (ConfigurationTestHelper.java:129)
  at fr.gaulupeau.apps.Poche.network.tasks.TestConnectionTask.onPostExecute (TestConnectionTask.java:129)
  at fr.gaulupeau.apps.Poche.network.tasks.TestConnectionTask.onPostExecute (TestConnectionTask.java:22)
```
Samsung Galaxy A51 5G (a51x), 5376MB RAM, Android 10:
```
java.lang.IllegalArgumentException:
  at android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:580)
  at android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:489)
  at android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:126)
  at android.app.Dialog.dismissDialog (Dialog.java:522)
  at android.app.Dialog.dismiss (Dialog.java:504)
  at fr.gaulupeau.apps.Poche.ui.preferences.ConfigurationTestHelper.dismissDialog (ConfigurationTestHelper.java:394)
  at fr.gaulupeau.apps.Poche.ui.preferences.ConfigurationTestHelper.onTestConnectionResult (ConfigurationTestHelper.java:129)
  at fr.gaulupeau.apps.Poche.network.tasks.TestConnectionTask.onPostExecute (TestConnectionTask.java:129)
  at fr.gaulupeau.apps.Poche.network.tasks.TestConnectionTask.onPostExecute (TestConnectionTask.java:22)
```
Motorola Moto G (5th Gen) (cedric), 2048MB RAM, Android 8.1:
```
java.lang.IllegalArgumentException:
  at android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:485)
  at android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:394)
  at android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:124)
  at android.app.Dialog.dismissDialog (Dialog.java:371)
  at android.app.Dialog.dismiss (Dialog.java:354)
  at fr.gaulupeau.apps.Poche.ui.preferences.ConfigurationTestHelper.dismissDialog (ConfigurationTestHelper.java:394)
  at fr.gaulupeau.apps.Poche.ui.preferences.ConfigurationTestHelper.onTestConnectionResult (ConfigurationTestHelper.java:129)
  at fr.gaulupeau.apps.Poche.network.tasks.TestConnectionTask.onPostExecute (TestConnectionTask.java:129)
  at fr.gaulupeau.apps.Poche.network.tasks.TestConnectionTask.onPostExecute (TestConnectionTask.java:22)
```
