### ISSUE TITLE
IllegalArgumentException: Invalid int: "OS" at TtsService.onInit

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#383]
reported on gdev console:

```
java.lang.IllegalArgumentException: Invalid int: "OS"
	at android.os.Parcel.readException(Parcel.java:1624)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.speech.tts.ITextToSpeechService$Stub$Proxy.getVoices(ITextToSpeechService.java:796)
	at android.speech.tts.TextToSpeech.getVoice(TextToSpeech.java:1769)
	at android.speech.tts.TextToSpeech.access$1100(TextToSpeech.java:59)
	at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1581)
	at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1531)
	at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2337)
	at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:747)
	at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:737)
	at android.speech.tts.TextToSpeech.setLanguage(TextToSpeech.java:1531)
	at fr.gaulupeau.apps.Poche.tts.TtsService.onInit(TtsService.java:526)
	at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:820)
	at android.speech.tts.TextToSpeech.access$1900(TextToSpeech.java:59)
	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2251)
	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2206)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

App-Version     
    29

Android-Version     
    Android 6.01

Gerät
    Galaxy S6 (zeroflte)

**Comment by di72nn** [comment]
https://code.google.com/p/android/issues/detail?id=80696
Not sure how to handle it.
