### ISSUE TITLE
app.wallabag.it prefilled config gives IncorrectConfigurationException: Incorrect URL

### ISSUE THREAD

**Issue by akwala** [wallabag/android-app#393]
After logging into app.wallabag.it, I went to https://app.wallabag.it/config and tapped the "Touch here to prefill" button under "Configure your Android application." This launched the app showing the config wizard with the URL and username prefilled. I entered the password and tapped CONNECT. 

The log excerpt corresponding to the above:

```
$ adb shell 'logcat | grep 9282'              
12-27 18:27:59.394  4066  4434 I ActivityManager: Start proc 9282:fr.gaulupeau.apps.InThePoche/u0a286 for activity fr.gaulupeau.apps.InThePoche/fr.gaulupeau.apps.Poche.ui.preferences.ConnectionWizardActivity
12-27 18:27:59.528  9282  9282 W System  : ClassLoader referenced unknown path: /data/app/fr.gaulupeau.apps.InThePoche-1/lib/arm
12-27 18:27:59.555  9282  9282 I LoadedApk: No resource references to update in package common
12-27 18:27:59.555  9282  9282 I LoadedApk: No resource references to update in package ideadesigns.theme.britzer
12-27 18:27:59.555  9282  9282 I LoadedApk: No resource references to update in package ind.aang.midnight.blue
12-27 18:27:59.556  9282  9282 I LoadedApk: No resource references to update in package ideadesigns.theme.britzer
12-27 18:27:59.737  9282  9282 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-27 18:27:59.774  9282  9282 D ConnectionWizard: onCreate() got data string: wallabag://username@https://app.wallabag.it
12-27 18:27:59.935  9282  9310 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-27 18:28:00.022  9282  9310 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
12-27 18:28:00.024  9282  9310 I OpenGLRenderer: Initialized EGL, version 1.4
12-27 18:29:09.015  9282  9713 D TestConnectionTask: Detecting redirection for: https://app.wallabag.it
12-27 18:29:10.154  9282  9713 D TestConnectionTask: URLs: 
12-27 18:29:10.154  9282  9713 D TestConnectionTask: https://app.wallabag.it
12-27 18:29:10.154  9282  9713 I TestConnectionTask: Testing https://app.wallabag.it
12-27 18:29:10.155  9282  9713 D WallabagService: getBodyFromHttpResponse() url=https://app.wallabag.it/api/version
12-27 18:29:10.625  9282  9713 D WallabagService: getBodyFromHttpResponse() response.code is not OK: 406
12-27 18:29:10.625  9282  9713 D WallabagService: isWallabagVersion2() did not find Wallabag v2
12-27 18:29:10.625  9282  9713 D WallabagService: getBodyFromHttpResponse() url=https://app.wallabag.it/?view=about
12-27 18:29:11.472  9282  9713 D WallabagService: isWallabagVersion1() did not find Wallabag v1
12-27 18:29:11.472  9282  9713 W WallabagService: Falling back to V2 endpoint; wallabagVersion=-1
12-27 18:29:12.342  9282  9713 D WallabagServiceEndpointV2: getCsrfToken() csrfTokenStartIndex=8990 and csrfTokenEndIndex=9033, so csrfTokenLength=43
12-27 18:29:12.342  9282  9713 D WallabagServiceEndpointV2: getCsrfToken() csrfToken=r4AzUn7NGq1INL5RScVfQ_EfdR_sFuSI0eSHtmizKS8
12-27 18:29:13.931  9282  9713 D TestConnectionTask: Connection test result: OK
12-27 18:29:13.960  9282  9282 D ConfigurationTestHelper: connectionTestOnSuccess() new url: https://app.wallabag.it
12-27 18:29:13.970  9282  9722 D WallabagService: getBodyFromHttpResponse() url=https://app.wallabag.it/api/version
12-27 18:29:14.444  9282  9722 D WallabagService: getBodyFromHttpResponse() response.code is not OK: 406
12-27 18:29:14.444  9282  9722 D WallabagService: isWallabagVersion2() did not find Wallabag v2
12-27 18:29:14.444  9282  9722 D WallabagService: getBodyFromHttpResponse() url=https://app.wallabag.it/?view=about
12-27 18:29:15.334  9282  9722 D WallabagService: isWallabagVersion1() did not find Wallabag v1
12-27 18:29:15.334  9282  9722 W WallabagService: Falling back to V2 endpoint; wallabagVersion=-1
12-27 18:29:15.334  9282  9722 D WallabagServiceEndpoint: getCredentials(): configPath=/config credentialsPattern="/(\S+)/([a-zA-Z0-9]+)/unread.xml"
12-27 18:29:15.335  9282  9722 D WallabagServiceEndpoint: getConfigRequest() url: https://app.wallabag.it/config
12-27 18:29:15.355  9282  9722 D WallabagServiceEndpointV2: executeRequestForResult(url: https://app.wallabag.it/config, checkResponse: true, autoRelogin: true) started
12-27 18:29:16.241  9282  9722 D WallabagServiceEndpointV2: executeRequestForResult() got response
12-27 18:29:16.250  9282  9722 D WallabagServiceEndpointV2: executeRequestForResult() response is login page
12-27 18:29:16.251  9282  9722 D WallabagServiceEndpointV2: executeRequestForResult() trying to re-login
12-27 18:29:17.135  9282  9722 D WallabagServiceEndpointV2: getCsrfToken() csrfTokenStartIndex=8990 and csrfTokenEndIndex=9033, so csrfTokenLength=43
12-27 18:29:17.135  9282  9722 D WallabagServiceEndpointV2: getCsrfToken() csrfToken=D_0MMZATwJI3xRzhwj32MExSNgkJTgmZb1Gm4oMBap4
12-27 18:29:17.135  9282  9722 D WallabagServiceEndpointV2: executeRequestForResult() csrfToken=D_0MMZATwJI3xRzhwj32MExSNgkJTgmZb1Gm4oMBap4
12-27 18:29:18.071  9282  9722 D WallabagServiceEndpointV2: executeRequestForResult() re-login response is OK; re-executing request
12-27 18:29:18.564  9282  9722 D WallabagServiceEndpointV2: executeRequestForResult() finished; returning page body
12-27 18:29:18.570  9282  9722 D WallabagServiceEndpoint: credentials=FeedsCredentials{userID='username', token='removedsensitivevalue'}
12-27 18:29:18.570  9282  9722 D WallabagService: getBodyFromHttpResponse() url=https://app.wallabag.it/api/version
12-27 18:29:18.996  9282  9722 D WallabagService: getBodyFromHttpResponse() response.code is not OK: 406
12-27 18:29:18.996  9282  9722 D WallabagService: isWallabagVersion2() did not find Wallabag v2
12-27 18:29:18.997  9282  9722 D WallabagService: getBodyFromHttpResponse() url=https://app.wallabag.it/?view=about
12-27 18:29:19.533  9282  9722 D WallabagService: isWallabagVersion1() did not find Wallabag v1
12-27 18:29:19.593  9282  9311 D TestFeedsTask: Exception
12-27 18:29:19.593  9282  9311 D TestFeedsTask: fr.gaulupeau.apps.Poche.network.exceptions.IncorrectConfigurationException: Incorrect URL
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at fr.gaulupeau.apps.Poche.network.WallabagConnection.getHttpURL(WallabagConnection.java:59)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at fr.gaulupeau.apps.Poche.network.FeedUpdater.getResponse(FeedUpdater.java:210)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at fr.gaulupeau.apps.Poche.network.tasks.TestFeedsTask.doInBackground(TestFeedsTask.java:70)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at fr.gaulupeau.apps.Poche.network.tasks.TestFeedsTask.doInBackground(TestFeedsTask.java:17)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-27 18:29:19.593  9282  9311 D TestFeedsTask:         at java.lang.Thread.run(Thread.java:818)
12-27 18:29:19.593  9282  9311 I TestFeedsTask: Result: UnknownError; details: Incorrect URL
12-27 18:29:35.550  9282  9282 W ConnectionWizard: onCreate() savedInstanceState != null
12-27 18:30:09.072  4066  4518 W InputMethodManagerService: Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@b1e6b5d (uid=10286 pid=9282)

```

**Comment by tcitworld** [comment]
Removed sensitive value from logs. We should remove the `FeedsCredentials{userID='username', token='removedsensitivevalue'}` log part.

Seems wallabag.it returned HTTP 406 for some reason. Some clue here @nicosomb ?
`WallabagService: getBodyFromHttpResponse() response.code is not OK: 406`

**Comment by akwala** [comment]
@tcitworld thanks! 

I thought I replaced the token, guess I missed one instance. Yes, sensitive stuff should not be written to logs.

**Comment by akwala** [comment]
Noticed that messages saying neither v2 nor v1 is found. Isn't this installation v2? 

>12-27 18:29:18.996  9282  9722 D WallabagService: isWallabagVersion2() did not find Wallabag v2
>... 
>12-27 18:29:19.533  9282  9722 D WallabagService: isWallabagVersion1() did not find Wallabag v1

**Comment by di72nn** [comment]
This is a server side issue: https://github.com/wallabag/wallabag/issues/2693 (either introduced in 2.2 or in wallabag.it configuration).

@nicosomb please do something ASAP.

@akwala sorry that you have to deal with errors *again*.

**Comment by nicosomb** [comment]
@di72nn I did a temporary fix on app.wallabag.it. This fix was removed yesterday (it's my fault). I re-added this fix just now. 
@akwala can you confirm that it's OK now for you?

**Comment by akwala** [comment]
Yes, connection succeeds now as does update/sync. I didn't see any exceptions in the log. Thanks.
