### ISSUE TITLE
Crash in master branch

### ISSUE THREAD

**Issue by ngosang** [wallabag/android-app#444]
wallabag-app master branch
* Fresh start
* Fill URL, user and password in connection assistant
* Press connect
* Crash

Hint; My URL is https://yyyy.xxxxx.org/wallabag/web/app.php

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                  Process: fr.gaulupeau.apps.InThePoche.debug, PID: 9315
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:304)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:831)
                   Caused by: java.lang.IllegalArgumentException: baseUrl must end in /: https://nexthop.duckdns.org/wallabag/web/app.php
                      at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:496)
                      at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:439)
                      at com.di72nn.stuff.wallabag.apiwrapper.WallabagService.<init>(WallabagService.java:545)
                      at fr.gaulupeau.apps.Poche.network.tasks.TestApiAccessTask.doInBackground(TestApiAccessTask.java:100)
                      at fr.gaulupeau.apps.Poche.network.tasks.TestApiAccessTask.doInBackground(TestApiAccessTask.java:16)
                      at android.os.AsyncTask$2.call(AsyncTask.java:292)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:831) 
```

**Comment by ngosang** [comment]
I fixed it changing:
Line 59 in TestApiAccessTask
        WallabagService wallabagService = new WallabagService(url+**"/"**, new ParameterHandler() {

After that another crash. I fixed it again changing:
Line 44 in WallabagServiceWrapper
        String url = settings.getUrl()+**"/"**;

Most of the app is working now but I don't see some images I can see in previous wallabag-app release.

**Comment by Strubbl** [comment]
Your url is wrong. it is https://yyyy.xxxxx.org/wallabag/web/ only. BTW, you shouldn't expose your whole wallabag/ directory, but only the web/ directory.

**Comment by di72nn** [comment]
First of all, thanks for reporting. Please do continue to report errors regarding wallabag installed in a subdirectory - there might be issues with it.

Is the "/app.php" part required? What happens without it?

I fixed the error by appending the slash directly in `WallabagService` with b8a1d88 in #440 (not in master yet).

> Most of the app is working now but I don't see some images I can see in previous wallabag-app release.

This is likely to be something else.
Did you by any change move your wallabag installation from a subdomain to a subdirectory recently? Or maybe other configuration changes? Do you use the feature to store article images on your server?

**Comment by ngosang** [comment]
> Your url is wrong. it is https://yyyy.xxxxx.org/wallabag/web/ only.

You are right. https://yyyy.xxxxx.org/wallabag/web/ and https://yyyy.xxxxx.org/wallabag/web are working in the browser. The URL I posted works too.

> BTW, you shouldn't expose your whole wallabag/ directory, but only the web/ directory.

Thank you for letting me know, but don't worry:
```
    <Directory /var/www/wallabag>
        Order Deny,Allow
        Deny from All
    </Directory>
```

> Is the "/app.php" part required?

Not, I thought it was.

I will answer the other questions this night.

**Comment by ngosang** [comment]
I tested Again:
**Web browser**
https://yyyy.xxxxx.org/wallabag/web => Works (using this now)
https://yyyy.xxxxx.org/wallabag/web/ => Works
https://yyyy.xxxxx.org/wallabag/web/app.php => Works

**Wallabag app 1.12.2 (Google play)**
https://yyyy.xxxxx.org/wallabag/web => Works (using this now)
https://yyyy.xxxxx.org/wallabag/web/ => It suggests me to use https://yyyy.xxxxx.org/wallabag/web instead
https://yyyy.xxxxx.org/wallabag/web/app.php => Works

**Wallabag app master branch**
https://yyyy.xxxxx.org/wallabag/web => **Crash reported in this issue**
https://yyyy.xxxxx.org/wallabag/web/ => It suggests me to use https://yyyy.xxxxx.org/wallabag/web instead and then **Crash reported in this issue**
https://yyyy.xxxxx.org/wallabag/web/app.php => **Crash reported in this issue**

> Did you by any chance move your wallabag installation from a subdomain to a subdirectory recently? Or maybe other configuration changes? Do you use the feature to store article images on your server?

No, but since it's working in wallabag app 1.12.2 (Google play) I think it doesn't matter.

**Comment by ngosang** [comment]
#440 fiixed all the issues:
**Wallabag app master branch**
https://yyyy.xxxxx.org/wallabag/web => Works (using this now)
https://yyyy.xxxxx.org/wallabag/web/ => It suggests me to use https://yyyy.xxxxx.org/wallabag/web instead
https://yyyy.xxxxx.org/wallabag/web/app.php => Works

I can't reproduce the images issue again.

**Comment by di72nn** [comment]
Thanks for the details.
