### ISSUE TITLE
Wallabag for Android: unable to "Download PDF"

### ISSUE THREAD

**Issue by nicosomb** [wallabag/android-app#521]
_From @returntrip on May 11, 2017 13:14_

### Issue details

Articles are not being downloaded as PDF in the Android app.

### Environment

* wallabag version (or git revision) that exhibits the issue: Android - ver 2.0.0b1
* How did you install wallabag? Via `git clone` or by downloading the package? Google Play
* Last wallabag version that did not exhibit the issue (if applicable): Not tested in other versions
* php version: NA
* OS: Android 7.1.2 stock on Nexus 6P
* type of hosting (shared or dedicated): shared
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):  NA

### Steps to reproduce/test case
On the Android app:

1) Open an article
2) From the drop down menu select: "Download PDF"
3) A progress bar will sit in the task bar saying: "wallabg downloads your article [article name]"
4) The article is not downloaded

_Copied from original issue: wallabag/wallabag#3109_

**Comment by tcitworld** [comment]
Logs : 
```
05-12 15:42:01.583 23692-28697/fr.gaulupeau.apps.InThePoche D/SecondaryService: downloadAsFile() started; action: DOWNLOAD_AS_FILE, articleID: 1275670
05-12 15:42:01.836 23692-23709/fr.gaulupeau.apps.InThePoche D/OpenGLRenderer: endAllActiveAnimators on 0xb0eb9d80 (MenuPopupWindow$MenuDropDownListView) with handle 0xb13e3ff0
05-12 15:42:02.168 23692-28697/fr.gaulupeau.apps.InThePoche D/SecondaryService: Saving file /storage/emulated/0/Android/data/fr.gaulupeau.apps.InThePoche/files/Microsoft_is_planning_to_turn_Windows_10_PCs_into_Amazon_Echo_competitors.pdf
05-12 15:42:02.175 23692-28697/fr.gaulupeau.apps.InThePoche D/EventProcessor: onDownloadFileFinishedEvent() started
05-12 15:42:02.182 23692-28697/fr.gaulupeau.apps.InThePoche E/EventBus: Could not dispatch event: class fr.gaulupeau.apps.Poche.events.DownloadFileFinishedEvent to subscribing class class fr.gaulupeau.apps.Poche.events.EventProcessor
                                                                        android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/fr.gaulupeau.apps.InThePoche/files/Microsoft_is_planning_to_turn_Windows_10_PCs_into_Amazon_Echo_competitors.pdf exposed beyond app through Intent.getData()
                                                                            at android.os.StrictMode.onFileUriExposed(StrictMode.java:1796)
                                                                            at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                            at android.content.Intent.prepareToLeaveProcess(Intent.java:8981)
                                                                            at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
                                                                            at android.app.PendingIntent.getActivity(PendingIntent.java:340)
                                                                            at android.app.PendingIntent.getActivity(PendingIntent.java:302)
                                                                            at fr.gaulupeau.apps.Poche.events.EventProcessor.onDownloadFileFinishedEvent(EventProcessor.java:373)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                            at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
                                                                            at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
                                                                            at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
                                                                            at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                                                                            at fr.gaulupeau.apps.Poche.events.EventHelper.postEvent(EventHelper.java:10)
                                                                            at fr.gaulupeau.apps.Poche.service.SecondaryService.downloadAsFile(SecondaryService.java:122)
                                                                            at fr.gaulupeau.apps.Poche.service.SecondaryService.onHandleIntent(SecondaryService.java:68)
                                                                            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
05-12 15:42:02.184 23692-28697/fr.gaulupeau.apps.InThePoche D/EventProcessor: onActionResultEvent() started
05-12 15:42:02.184 23692-28697/fr.gaulupeau.apps.InThePoche D/EventProcessor: onActionResultEvent() action: DOWNLOAD_AS_FILE
05-12 15:42:02.184 23692-28697/fr.gaulupeau.apps.InThePoche D/EventProcessor: onActionResultEvent() result is success: true
05-12 15:42:02.184 23692-28697/fr.gaulupeau.apps.InThePoche D/SecondaryService: onHandleIntent() finished
```

**Comment by Strubbl** [comment]
Yes, i can reproduce it:

```
05-12 17:46:26.243 8428-8491/fr.gaulupeau.apps.InThePoche.debug D/EventProcessor: onDownloadFileFinishedEvent() started
05-12 17:46:26.246 8428-8491/fr.gaulupeau.apps.InThePoche.debug E/AndroidRuntime: FATAL EXCEPTION: IntentService[SecondaryService]
                                                                                  Process: fr.gaulupeau.apps.InThePoche.debug, PID: 8428
                                                                                  org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
                                                                                      at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
                                                                                      at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
                                                                                      at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
                                                                                      at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
                                                                                      at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
                                                                                      at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                                                                                      at fr.gaulupeau.apps.Poche.events.EventHelper.postEvent(EventHelper.java:10)
                                                                                      at fr.gaulupeau.apps.Poche.service.SecondaryService.downloadAsFile(SecondaryService.java:122)
                                                                                      at fr.gaulupeau.apps.Poche.service.SecondaryService.onHandleIntent(SecondaryService.java:68)
                                                                                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:241)
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                   Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/fr.gaulupeau.apps.InThePoche.debug/files/Open_VPN_behebt_nach_Audits_Sicherheitsm_ngel___Linux-Magazin.pdf exposed beyond app through Intent.getData()
                                                                                      at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                                      at android.net.Uri.checkFileUriExposed(Uri.java:2351)
                                                                                      at android.content.Intent.prepareToLeaveProcess(Intent.java:9011)
                                                                                      at android.content.Intent.prepareToLeaveProcess(Intent.java:8972)
                                                                                      at android.app.PendingIntent.getActivity(PendingIntent.java:340)
                                                                                      at android.app.PendingIntent.getActivity(PendingIntent.java:302)
                                                                                      at fr.gaulupeau.apps.Poche.events.EventProcessor.onDownloadFileFinishedEvent(EventProcessor.java:373)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                                      at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416) 
                                                                                      at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397) 
                                                                                      at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370) 
                                                                                      at org.greenrobot.eventbus.EventBus.post(EventBus.java:251) 
                                                                                      at fr.gaulupeau.apps.Poche.events.EventHelper.postEvent(EventHelper.java:10) 
                                                                                      at fr.gaulupeau.apps.Poche.service.SecondaryService.downloadAsFile(SecondaryService.java:122) 
                                                                                      at fr.gaulupeau.apps.Poche.service.SecondaryService.onHandleIntent(SecondaryService.java:68) 
                                                                                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:241) 
                                                                                      at android.os.HandlerThread.run(HandlerThread.java:61) 
05-12 17:46:26.511 8428-8428/fr.gaulupeau.apps.InThePoche.debug I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@316f4b1 time:137929945
05-12 17:46:26.513 8428-8428/fr.gaulupeau.apps.InThePoche.debug V/ReadArticleActivity: getReadingPosition() yOffset: 0, viewHeight: 1024, totalHeight: 4244
```

i am goint to test di72nn's fix now and will report back in the PR
