### ISSUE TITLE
IllegalStateException at SecondaryService.fetchImages(SecondaryService.java:278)

### ISSUE THREAD

**Issue by Strubbl** [wallabag/android-app#566]
from gplay, reported 395 times (this week 167, from 3 users) 

```
java.lang.IllegalStateException: 
  at android.database.CursorWindow.nativeGetLong(Native Method:0)
  at android.database.CursorWindow.getLong(CursorWindow.java:511)
  at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
  at org.greenrobot.greendao.AbstractDao.loadCurrent(AbstractDao.java:541)
  at org.greenrobot.greendao.AbstractDao.loadAllUnlockOnWindowBounds(AbstractDao.java:498)
  at org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java:480)
  at org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:203)
  at org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
  at org.greenrobot.greendao.query.Query.list(Query.java:89)
  at org.greenrobot.greendao.query.QueryBuilder.list(QueryBuilder.java:427)
  at fr.gaulupeau.apps.Poche.service.SecondaryService.fetchImages(SecondaryService.java:278)
  at fr.gaulupeau.apps.Poche.service.SecondaryService.onHandleIntent(SecondaryService.java:76)
  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.os.HandlerThread.run(HandlerThread.java:61)

```
https://github.com/wallabag/android-app/blob/2.0.0/app/src/main/java/fr/gaulupeau/apps/Poche/service/SecondaryService.java#L278

Zeitstempel des Berichts

Heute, 21:57

App-Version

104

Android-Version

Android 7.1

Gerät
HTC One (m7)

Hersteller
    HTC
RAM (MB)
    2048
Bildschirmgröße
    1080 × 1920
Bildschirmdichte (dpi)
    480
Native Plattform
    armeabi-v7a
OpenGL ES-Version
    2.0
CPU-Marke
    Qualcomm
CPU-Modell
    APQ8064

**Comment by di72nn** [comment]
Also
```
java.lang.IllegalStateException: 
  at android.database.CursorWindow.nativeGetLong(Native Method:0)
  at android.database.CursorWindow.getLong(CursorWindow.java:511)
  at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
  at org.greenrobot.greendao.AbstractDao.loadCurrent(AbstractDao.java:541)
  at org.greenrobot.greendao.AbstractDao.loadAllUnlockOnWindowBounds(AbstractDao.java:498)
  at org.greenrobot.greendao.AbstractDao.loadAllFromCursor(AbstractDao.java:480)
  at org.greenrobot.greendao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:203)
  at org.greenrobot.greendao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:37)
  at org.greenrobot.greendao.query.Query.list(Query.java:89)
  at org.greenrobot.greendao.query.QueryBuilder.list(QueryBuilder.java:427)
  at fr.gaulupeau.apps.Poche.ui.ArticleListFragment.getItems(ArticleListFragment.java:170)
  at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment.loadMore(RecyclerViewListFragment.java:201)
  at fr.gaulupeau.apps.Poche.ui.RecyclerViewListFragment$1.onLoadMore(RecyclerViewListFragment.java:82)
  at fr.gaulupeau.apps.Poche.ui.EndlessRecyclerViewScrollListener.onScrolled(EndlessRecyclerViewScrollListener.java:96)
  at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4618)
  at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4776)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
  at android.view.Choreographer.doCallbacks(Choreographer.java:686)
  at android.view.Choreographer.doFrame(Choreographer.java:618)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6178)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```


Report timestamp

May 21, 8:29 PM

Application version

104

Android version

Android 7.1

Device
LG G3 (g3)

Manufacturer
    LGE
RAM (MB)
    3072
Screen size
    1440 × 2560
Screen density (dpi)
    640
Native platform
    armeabi-v7a
OpenGL ES version
    3.0
CPU make
    Qualcomm
CPU model
    MSM8974AC

**Comment by di72nn** [comment]
Google have taken the last means of determining the reasons of exceptions: the exception messages.

I can only guess that it is the same as #413.

**Comment by di72nn** [comment]
#413.
