### ISSUE TITLE
User can't sync with https

### ISSUE THREAD

**Issue by tcitworld** [wallabag/android-app#58]
Hi,
An user emailed me with a sync problem. With his credentials, I did manage to sync.
His logcat showed : 
```
12-16 21:41:45.776 W/System.err(28579): javax.net.ssl.SSLException: Connection closed by peer
12-16 21:41:45.776 W/System.err(28579): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.okhttp.Connection.connect(Connection.java:107)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
12-16 21:41:45.776 W/System.err(28579): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
12-16 21:41:45.786 W/System.err(28579): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
12-16 21:41:45.786 W/System.err(28579): 	at fr.gaulupeau.apps.Poche.Poche.parseRSS(Poche.java:413)
12-16 21:41:45.786 W/System.err(28579): 	at fr.gaulupeau.apps.Poche.Poche$1$1.run(Poche.java:177)
12-16 21:41:45.786 W/System.err(28579): 	at java.lang.Thread.run(Thread.java:841)
```
[(full file)](https://gist.github.com/tcitworld/97b4d562aa6bd75b8c1b)

Any idea why this happens ?

**Comment by blitzmohit** [comment]
Could someone confirm the if a self generated certificate is being used for the https server ? I think the problem could be related to that.

**Comment by tcitworld** [comment]
Anyway, you can now ignore trust for self-signed certificates.
