### ISSUE TITLE
Couldn't read row 0, col -1 from CursorWindow

### ISSUE THREAD

**Issue by nischayvaish1996** [wallabag/android-app#653]
**logcat**

```ot late-enabling -Xcheck:jni (already on)
11-09 19:08:15.924 12588-12588/? W/art: Unexpected CPU variant for X86 using defaults: x86
11-09 19:08:15.977 12588-12595/? I/art: Debugger is no longer active
11-09 19:08:15.977 12588-12595/? I/art: Starting a blocking GC Instrumentation
11-09 19:08:16.113 12588-12588/? W/System: ClassLoader referenced unknown path: /data/app/nischayvaish.com.test1-1/lib/x86
11-09 19:08:16.125 12588-12588/? I/InstantRun: starting instant run server: is main process
11-09 19:08:16.325 12588-12588/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
11-09 19:08:16.555 12588-12588/? E/CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 4 rows, 2 columns.
11-09 19:08:16.555 12588-12588/? D/AndroidRuntime: Shutting down VM
11-09 19:08:16.555 12588-12588/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: nischayvaish.com.test1, PID: 12588
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{nischayvaish.com.test1/nischayvaish.com.test1.MainActivity}: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                    Caused by: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                       at android.database.CursorWindow.nativeGetLong(Native Method)
                                                       at android.database.CursorWindow.getLong(CursorWindow.java:511)
                                                       at android.database.CursorWindow.getInt(CursorWindow.java:578)
                                                       at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
                                                       at nischayvaish.com.test1.MainActivity.readFromDb(MainActivity.java:61)
                                                       at nischayvaish.com.test1.MainActivity.onCreate(MainActivity.java:40)
                                                       at android.app.Activity.performCreate(Activity.java:6662)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

**DbHelper.class**
`public class DbHelper extends SQLiteOpenHelper {
    private static final String DATABASE_NAME = "numberDb";
    private static final int DATABASE_VERSION = 1;
    private static final String CREATE = "CREATE TABLE " + DbContract.TABLE_NAME + "(ID INTEGER PRIMARY KEY AUTOINCREMENT," + DbContract.INCOMING_NUMBER + " TEXT);";
    private static final String DROP_TABLE = "drop table if exists " + DbContract.TABLE_NAME;

    public DbHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);

    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(CREATE);

    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL(DROP_TABLE);
        onCreate(db);
    }

    public void saveNumber(String number, SQLiteDatabase database) {
        ContentValues contentValues = new ContentValues();
        contentValues.put(DbContract.INCOMING_NUMBER, number);
        Log.e(number,"incoming nuumber");
        database.insert(DbContract.TABLE_NAME, null, contentValues);
    }

    public Cursor readNumber(SQLiteDatabase database) {
        String[] projection = {"id", DbContract.INCOMING_NUMBER};
        return (database.query(DbContract.TABLE_NAME, projection, null, null, null, null, null));
    }`
**MainActivity.class**

`private TextView tv1;
    private RecyclerView recycler_view;
    private RecyclerView.LayoutManager layoutManager;
    private ArrayList<IncomingNumber> arrayList = new ArrayList<>();
    private RecyclerAdapter adapter;
    private BroadcastReceiver broadcastReceiver;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        tv1 = (TextView) findViewById(R.id.emptyTxt);
        recycler_view = (RecyclerView) findViewById(R.id.recyclerView);
        layoutManager = new LinearLayoutManager(this);
        recycler_view.setLayoutManager(layoutManager);
        recycler_view.setHasFixedSize(true);
        adapter = new RecyclerAdapter(arrayList);
        recycler_view.setAdapter(adapter);
        readFromDb();
        broadcastReceiver = new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                readFromDb();
            }
        };

    }

    private void readFromDb() {
        arrayList.clear();
        DbHelper dbHelper = new DbHelper(this);
        SQLiteDatabase database = dbHelper.getWritableDatabase();
        Cursor cursor = dbHelper.readNumber(database);
        if (cursor.getCount() > 0) {
            while (cursor.moveToNext())
            {
                String number;
                int id;
                number = cursor.getString(cursor.getColumnIndex(DbContract.INCOMING_NUMBER));
                id = cursor.getInt(cursor.getColumnIndex("id"));
                Log.e(number,"incoming_number");
                arrayList.add(new IncomingNumber(id, number));
            }
            cursor.close();
            dbHelper.close();
            adapter.notifyDataSetChanged();
            recycler_view.setVisibility(View.VISIBLE);
            tv1.setVisibility(View.GONE);
        }

    }

    @Override
    protected void onResume() {
        super.onResume();
        registerReceiver(broadcastReceiver, new IntentFilter(DbContract.UPDATE_UI_FILTER));
    }

    @Override
    protected void onPause() {
        super.onPause();
        unregisterReceiver(broadcastReceiver);
    }`
Application does not show number while the Log is printing the number

**Comment by Strubbl** [comment]
What is your problem? You are just posting unrelated logcat output

**Comment by nischayvaish1996** [comment]
logcat show the same output,
I am at beginner level so I didn't understand the error in this code.
The main problem is that the application does not show any data while the log can show.

**Comment by Strubbl** [comment]
Okay, but i do not understand your problem. What are you trying to do? What is your expected reaction? What actually happens?
Whats your Android version?
Whats your Android hardware?
Which version of the wallabag android app have you installed?
How did you install it? (e.g. via Google Play or F-Droid...)
Which version of wallabag do you run on the server?

The logcat output says the error happens in `Process: nischayvaish.com.test1, PID: 12588`. How is that process related to the wallabag android app?
