### ISSUE TITLE
Can't login to Version: 2.4.0-dev

### ISSUE THREAD

**Issue by alxchk** [wallabag/android-app#834]
1. Upgraded wallabag on the server to the current master (2.4,  last commit 63e4ce5ce3f8b8514b8bbd8ae557768a8669ec0f)
2. Logout/Login in browser -> ok
3. Logout/Login in mobile app -> failed
In logs:
[2019-09-13 09:38:49] request.INFO: Matched route "api_get_version". {"route":"api_get_version","route_parameters":{"_controller":"Wallabag\\ApiBundle\\Controller\\UserRestController::getVersionAction","_format":"json","_route":"api_get_version"},"request_uri":"https://XXXX.XXXXXXXXX.XXX/api/version.json","method":"GET"} []
[2019-09-13 09:38:49] app.ERROR: Authentication failure for user "", from IP "XXX.XXX.XXX.XXX", with UA: "okhttp/3.14.2". [] []

Please note, that in logs user is empty -> ""

Also tried with latest apk from releases page -> same behavior

**Comment by di72nn** [comment]
What kind of error does the app show?
Have you tried running the connection wizard? It should show a specific error.

This log message for `api/version` is [an unrelated issue](https://github.com/wallabag/wallabag/issues/3575).

**Comment by alxchk** [comment]
The app doesn't show error. Actually it doesn't show anything special.

Here are some things from adb:

```
09-13 13:54:07.437  2849  2998 I WallabagService: intercept() unsuccessful response; code: 401
09-13 13:54:07.437  2849  2998 I WallabagService: Access token requested
09-13 13:54:07.438  2849  2998 I WallabagService: Refreshing token
09-13 13:54:07.438  2849  2998 I WallabagService: started
09-13 13:54:07.439  2849  2998 I WallabagService: Requesting new token
09-13 13:54:07.439  2849  2998 I WallabagService: started
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: doInBackground() UnsuccessfulResponseException with body: {"error":"invalid_client","error_description":"The client credentials are invalid"}
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: com.di72nn.stuff.wallabag.apiwrapper.exceptions.AuthorizationException: HTTP response: 400 Bad Request
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at com.di72nn.stuff.wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:895)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at com.di72nn.stuff.wallabag.apiwrapper.WallabagService.getVersion(WallabagService.java:878)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at fr.gaulupeau.apps.Poche.network.tasks.TestApiAccessTask.doInBackground(TestApiAccessTask.java:101)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at fr.gaulupeau.apps.Poche.network.tasks.TestApiAccessTask.doInBackground(TestApiAccessTask.java:16)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-13 13:54:07.816  2849  2998 W TestApiAccessTask: 	at java.lang.Thread.run(Thread.java:764)
09-13 13:54:14.077  2849  2998 D TestConnectionTask: Detecting redirection for: https://XXX.XXXXXXX.XX
09-13 13:54:14.534  2849  2998 D TestConnectionTask: URLs: 
09-13 13:54:14.534  2849  2998 D TestConnectionTask: https://XXX.XXXXXXX.XX
09-13 13:54:14.534  2849  2998 I TestConnectionTask: Testing https://XXX.XXXXXXX.XX
09-13 13:54:15.489  2849  2998 D TestConnectionTask: Connection test result: OK
```

**Comment by di72nn** [comment]
From the logs I can gather that web-based authorization seems to work ok, but can't say anything about API access.

Have you tried going all the way through with the connection wizard? Does it finish successfully?
Can you capture the adb logs while going from start to finish of the connection wizard?

**Comment by alxchk** [comment]
This is from wizard. 
[x.log](https://github.com/wallabag/android-app/files/3609951/x.log)

**Comment by di72nn** [comment]
Thanks, that helps a lot. The important part seems to be this:
```
09-13 13:54:05.760  2849  2997 D WallabagWebService: getApiClientCredentials() configPath: /config
09-13 13:54:05.761  2849  2997 D WallabagWebService: executeRequestForResult(url: https://XXX.XXXXXXX.XXXXX/developer, checkResponse: true, autoRelogin: true) started
09-13 13:54:06.203  2849  2997 D WallabagWebService: executeRequestForResult() got response
09-13 13:54:06.204  2849  2997 D WallabagWebService: executeRequestForResult() response is login page
09-13 13:54:06.204  2849  2997 D WallabagWebService: executeRequestForResult() trying to re-login
09-13 13:54:06.446  2849  2997 D WallabagWebService: executeRequestForResult() csrfToken=VGvPs_Y7rJHuvAEgrZmptDEho8zVUYWdLApLocnnj1o
09-13 13:54:06.804  2849  2997 D WallabagWebService: executeRequestForResult() re-login response is OK; re-executing request
09-13 13:54:06.954  2849  2997 D WallabagWebService: executeRequestForResult() finished; returning page body
09-13 13:54:06.954  2849  2997 D WallabagWebService: getApiClientCredentials() found client: Android app - #3
09-13 13:54:06.955  2849  2997 D WallabagWebService: getApiClientCredentials() client ID: [null]
```
Specifically `client ID: [null]`. It's also not a Java `null`, but a string literal `[null]`.

@alxchk can you check that the `https://XXX.XXXXXXX.XXXXX/developer` page has sane values for the "Client ID" and "Client secret" fields (at least for the `Android app - #3` client)?

**Comment by alxchk** [comment]
```
Client ID / Client secret - present,
Redirect URIs - [null]
```

**Comment by alxchk** [comment]
Okay, looks like automatic parsing for client ID and client secret is broken. 
I copied them manually, and app works. 

Looks like value from Redirect URI goes to Client ID and value from Grant type allowed goes to Client secret
