### ISSUE TITLE
Wallabag crashes immediately after fresh install (Samsung Note 10+)

### ISSUE THREAD

**Issue by glego** [wallabag/android-app#863]
# Issue details

### Duplicate?
No

### Actual behaviour
The app crashes immediately after starting.

### Expected behaviour
The app should start.

### What have you tried to resolve the issue?
- Reinstall the app

# Steps to reproduce the issue
1. Install the app on a Samsung Note10+
2. Start the app

# Environment details
- **wallabag app version**: latest 2.2.4
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Google Play Store
- **Android OS version**: 9
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock
- **Android hardware**: Samsung Note 10+
- **wallabag server version**:  Version: 2.3.3
- **Do you have Two-Factor-Authentication enabled?**: no

# Logs
## adb logcat
[logcat.zip](https://github.com/wallabag/android-app/files/3790556/logcat.zip)

# Your experience with wallabag Android app
I switched my phone this week and put all the effort into getting the log file. Wallabag has become essential in organizing my reading material. I would hate to switch to another product because I'm unable to use the app! Keep up the good work!

Thanks,
Glenn

**Comment by tcitworld** [comment]
Relevant logs:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lnet/sqlcipher/database/SQLiteOpenHelper;
```

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.sqlcipher.database.SQLiteOpenHelper" on path: DexPathList[[zip file "/data/app/fr.gaulupeau.apps.InThePoche-7zt_6GPSSx7cGpXYmMEW_w==/base.apk", zip file "/data/app/fr.gaulupeau.apps.InThePoche-7zt_6GPSSx7cGpXYmMEW_w==/split_config.en.apk", zip file "/data/app/fr.gaulupeau.apps.InThePoche-7zt_6GPSSx7cGpXYmMEW_w==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/fr.gaulupeau.apps.InThePoche-7zt_6GPSSx7cGpXYmMEW_w==/lib/arm64, /system/lib64]]
```

```
SQLiteLog: (28) failed to open "/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche/files/wallabag" with flag (131138) and mode_t (0) due to error (2)
10-30 18:57:00.624  5651  5722 W SQLiteLog: (28) failed to open "/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche/files/wallabag" with flag (131072) and mode_t (0) due to error (2)
10-30 18:57:00.624  5651  5722 E SQLiteLog: (14) cannot open file at line 37564 of [c255889bd9]
10-30 18:57:00.624  5651  5722 E SQLiteLog: (14) os_unix.c:37564: (2) open(/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche/files/wallabag) - 
10-30 18:57:00.625  5651  5722 E SQLiteLog: (1) Process apps.InThePoche : Pid (5651) Uid (10385) Euid (10385) Gid (10385) Egid (10385)
10-30 18:57:00.625  5651  5722 E SQLiteLog: (1) osStat failed "/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche/files/wallabag" due to error (2)
10-30 18:57:00.625  5651  5722 E SQLiteLog: (1) osStat failed "/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche/files" due to error (2)
10-30 18:57:00.625  5651  5722 E SQLiteLog: (1) osStat failed "/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche" due to error (2)
10-30 18:57:00.625  5651  5722 E SQLiteLog: (1) osStat failed "/storage/3A4D-7528/Android/data" due to error (2)
10-30 18:57:00.625  5651  5722 E SQLiteLog: (1) osStat failed "/storage/3A4D-7528/Android" due to error (2)
10-30 18:57:00.625  5651  5722 E SQLiteLog: (1) osStat failed "/storage/3A4D-7528" due to error (2)
10-30 18:57:00.625  5651  5722 E SQLiteLog: (1) Stat of /storage : st_mode(40755) st_uid(0) st_gid(0) st_ino(16075)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: Failed to open database '/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche/files/wallabag'.
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 1294 SQLITE_CANTOPEN_ENOENT[1294]): Could not open database
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:284)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:705)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:272)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:239)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1292)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1247)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:903)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:893)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:355)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at org.greenrobot.greendao.database.DatabaseOpenHelper.getWritableDb(DatabaseOpenHelper.java:59)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at fr.gaulupeau.apps.Poche.data.DbConnection.getSession(DbConnection.java:45)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at fr.gaulupeau.apps.Poche.data.DbConnection$Holder.<clinit>(DbConnection.java:69)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at fr.gaulupeau.apps.Poche.data.DbConnection$Holder.access$000(DbConnection.java:68)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at fr.gaulupeau.apps.Poche.data.DbConnection.getSession(DbConnection.java:31)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at fr.gaulupeau.apps.Poche.service.IntentServiceBase.getDaoSession(IntentServiceBase.java:99)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at fr.gaulupeau.apps.Poche.service.MainService.getUpdater(MainService.java:493)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at fr.gaulupeau.apps.Poche.service.MainService.updateArticles(MainService.java:430)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at fr.gaulupeau.apps.Poche.service.MainService.onHandleIntent(MainService.java:100)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.os.Looper.loop(Looper.java:216)
10-30 18:57:00.625  5651  5722 E SQLiteDatabase: 	at android.os.HandlerThread.run(HandlerThread.java:65)
10-30 18:57:00.625  5651  5722 D EventProcessor: onUpdateArticlesFinishedEvent() started
10-30 18:57:00.625  5651  5651 D AndroidRuntime: Shutting down VM
```

**Comment by Strubbl** [comment]
```
java.lang.NoClassDefFoundError: Failed resolution of: Lnet/sqlcipher/database/SQLiteOpenHelper;
```
The line seems to be unrelated to this issue. It was already present in the log of issue #856

**Comment by glego** [comment]
Hi,

I've installed the version 2.2.3 manually from github, and it seems to work fine. When installing 2.2.4 from github I get the same issue.

https://github.com/wallabag/android-app/releases/tag/2.2.3

**Comment by di72nn** [comment]
I'm pretty sure we don't need `net/sqlcipher/database/SQLiteOpenHelper`.

There's nothing in the diff between 2.2.3 and 2.2.4 that could cause a DB-related error.

`/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche/files/wallabag` seems like external storage, which we don't use by default.

@glego are you sure it is a clean installation? Maybe some kind of app data backup (by Google or Samsung) kicks in and restores incorrect settings? Can you try manually cleaning app data after installation? Can you also try the latest beta?

**Comment by glego** [comment]
I'm actually able to reproduce the issue over and over by uninstalling the app and installing 2.2.4 or the2.3.0-beta.4 first. If I install the 2.2.3 first and then upgrade everything works fine.

I don't think its a DB-related issues, yes there is an exception but it doesn't seem to crash the app completely.  The fatal error initiated by the FragmentManager seem to be the root cause, and also explains why 2.2.3 is working.

Video proof: https://www.youtube.com/watch?v=YU5RZBz5LAU

Also in the original log you can see the event happening:
```
10-30 18:57:00.625  5651  5651 E AndroidRuntime: FATAL EXCEPTION: main
10-30 18:57:00.625  5651  5651 E AndroidRuntime: Process: fr.gaulupeau.apps.InThePoche, PID: 5651
10-30 18:57:00.625  5651  5651 E AndroidRuntime: java.lang.NoClassDefFoundError: <clinit> failed for class fr.gaulupeau.apps.Poche.data.DbConnection$Holder; see exception in other thread
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at fr.gaulupeau.apps.Poche.data.DbConnection$Holder.access$000(DbConnection.java:68)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at fr.gaulupeau.apps.Poche.data.DbConnection.getSession(DbConnection.java:31)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at fr.gaulupeau.apps.Poche.ui.ArticleListFragment.onCreate(ArticleListFragment.java:86)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:146)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1244)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7741)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7741)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7741)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7741)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7741)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7741)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7741)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7741)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1050)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.View.measure(View.java:25044)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3382)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2104)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2403)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1964)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8720)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:765)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:700)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7263)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
10-30 18:57:00.625  5651  5651 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by di72nn** [comment]
I downloaded the APKs from github, decoded them with `apktool` and the differences seem to correspond to the git diff. Which shouldn't break anything (at least not without something relevant in the logs).

> I don't have external storage installed on my phone.

I'm not sure how it's called these days, but I meant the "public storage" (which contains photos and stuff) as opposed to "internal/private storage" (which is separate for each app). I'm pretty sure the path in the logs (`/storage/3A4D-7528/Android/data/fr.gaulupeau.apps.InThePoche/files/wallabag`) is that "public storage", which should only be accessed by the app only if it was set in settings (Settings - Misc - Database location - External storage).

I set the DB location to "external storage", via `adb` (with root) edited the preferences file (`/data/data/fr.gaulupeau.apps.InThePoche.debug/fr.gaulupeau.apps.InThePoche.debug_preferences.xml`) changing `storage.dbPath` to a path that cannot be created and got **very** similar error (considering that I run different Android version it might as well be the same error).

My current theory (even though it's a bit far-fetched) is that something like this happens:
 * You install 2.2.4.
 * Something restores old settings from a backup.
 * You uninstall the app, install 2.2.3.
 * Nothing is restored because the version is lower than the one the backup was saved for.
 * You upgrade to 2.2.4.
 * Nothing is restored because it is an upgrade, not an installation.

@glego have you tried installing 2.2.3 then **without** starting the app updating it to 2.2.4?

Also when you do a clean install of 2.2.4, can you manually check and clean app data? Then start the app and if it crashes, clean the app data again and try to start it again.

**Comment by glego** [comment]
> @glego have you tried installing 2.2.3 then without starting the app updating it to 2.2.4?

This actually worked, so your theory seems to be right that something is restoring my settings (most likely google backup).

>  Can you try manually cleaning app data after installation?

I should have tested this, this actually worked. I installed 2.2.4 from the Google Play store, cleared the data and the app started.

> you may also check whether your new or old phone has that /storage/3A4D-7528/ path, but just out of curiosity, it won't really help much.

It could be, the path sounds familiar, it was a Samsung S7 with external SD card.

Thanks allot for your time and effort, even though it is not caused by you guys... I'll try to find how to delete these backups from Google... I can't seem to find any setting to do this.

I donated another € 20 on PayPal (yesterday € 10), thanks allot.

**Comment by di72nn** [comment]
Glad it got sorted out. Thanks for the donation!

**Comment by papombo** [comment]
> 
> # Issue details
> ### Duplicate?
> 
> No
> ### Actual behaviour
> 
> The app crashes immediately after starting.
> ### Expected behaviour
> 
> The app should start.
> ### What have you tried to resolve the issue?
> 
>     * Reinstall the app
> 
> 
> # Steps to reproduce the issue
> 
>     1. Install the app on a Samsung Note10+
> 
>     2. Start the app
> 
> 
> # Environment details
> 
>     * **wallabag app version**: latest 2.2.4
> 
>     * **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Google Play Store
> 
>     * **Android OS version**: 9
> 
>     * **Android ROM** (e.g. stock, LineageOS, SlimRom,…): Stock
> 
>     * **Android hardware**: Samsung Note 10+
> 
>     * **wallabag server version**:  Version: 2.3.3
> 
>     * **Do you have Two-Factor-Authentication enabled?**: no
> 
> 
> # Logs
> ## adb logcat
> 
> [logcat.zip](https://github.com/wallabag/android-app/files/3790556/logcat.zip)
> # Your experience with wallabag Android app
> 
> I switched my phone this week and put all the effort into getting the log file. Wallabag has become essential in organizing my reading material. I would hate to switch to another product because I'm unable to use the app! Keep up the good work!
> 
> Thanks,
> Glenn

I'm facing this issue on build 2.4.0 on Android 10. My phone is a Sony Xperia XZ 2 Premium.

**Comment by di72nn** [comment]
@papombo create a new issue.
